# This is a minimal makefile only used for the examples. If you want a makefile
# for your project, take one from the templates inside examples/templates.

BINDIRS		:= data
AUDIODIRS	:= audio

DEFINES		:= -DNEA_MAXMOD
LIBS		:= -lNEA -lmm9 -lnds9 -lc
LIBDIRS		+= $(BLOCKSDS)/libs/maxmod
ARM7ELF		:= $(BLOCKSDS)/sys/arm7/main_core/arm7_maxmod.elf

include ../../Makefile.example
