// SPDX-License-Identifier: CC0-1.0
//
// Generated by gen_vectors.py. Do not edit.

#ifndef VECTORS_H__
#define VECTORS_H__

#include <stdint.h>

typedef struct {
    const char *path;
    uint32_t size;
    uint32_t crc;
    uint8_t method;
} TestVector;

static const TestVector vectors[] = {
    { "long_nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn.bin", 19, 0x2D656C80U, 0x00 },
    { "odd.bin", 1023, 0xD15E811FU, 0x00 },
    { "stored.bin", 1024, 0xE989847DU, 0x00 },
    { "zero.bin", 0, 0x00000000U, 0x00 },
    { "a/b/c/deep.bin", 300, 0xD1B2522FU, 0x00 },
    { "huff/skew.bin", 4096, 0x851B485EU, 0x28 },
    { "lz/text.txt", 4096, 0xFBC2504CU, 0x10 },
    { "rle/runs.bin", 4096, 0xA6927B81U, 0x30 },
};

#define NUM_VECTORS (sizeof(vectors) / sizeof(vectors[0]))

typedef struct {
    const char *name;
    bool is_dir;
} TestDirEntry;

typedef struct {
    const char *path;
    const TestDirEntry *entries;
    int count;
} TestListing;

static const TestDirEntry listing_0[] = {
    { "a", true },
    { "huff", true },
    { "lz", true },
    { "rle", true },
    { "long_nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn.bin", false },
    { "odd.bin", false },
    { "stored.bin", false },
    { "zero.bin", false },
};

static const TestDirEntry listing_1[] = {
    { "c", true },
};

static const TestListing listings[] = {
    { "/", listing_0, 8 },
    { "/a/b", listing_1, 1 },
};

#define NUM_LISTINGS (sizeof(listings) / sizeof(listings[0]))

#endif // VECTORS_H__
