// SPDX-License-Identifier: CC0-1.0
//
// SPDX-FileContributor: Warioware64, 2026
//
// This file is part of Nitro Engine Advanced
//
// Hardware 2D OBJ sprite example
// ------------------------------
// Shows hardware OBJ sprites (statue) overlaid on a 3D scene.
// Bank B is used for main sprites, Banks A+C+D remain for 3D textures.
// Sprite data is converted from statue.png by grit (8bpp tiled format).

#include <NEAMain.h>

// Auto-generated by grit from statue.png
#include "statue.h"

#define NUM_SPRITES 3

typedef struct {
    NEA_Camera *camera;
} SceneData;

void Draw3DScene(void *arg)
{
    SceneData *scene = arg;
    NEA_CameraUse(scene->camera);

    // Simple 3D triangle in the background
    NEA_PolyFormat(31, 0, NEA_LIGHT_0, NEA_CULL_NONE, 0);

    GFX_BEGIN = GL_TRIANGLES;
    GFX_COLOR = RGB15(20, 20, 20);
    glVertex3v16(floattov16(-2.0), floattov16(-1.5), 0);
    glVertex3v16(floattov16(2.0), floattov16(-1.5), 0);
    glVertex3v16(floattov16(0.0), floattov16(1.5), 0);
    GFX_END = 0;
}

int main(int argc, char *argv[])
{
    (void)argc;
    (void)argv;

    SceneData scene = { 0 };

    irqEnable(IRQ_HBLANK);
    irqSet(IRQ_VBLANK, NEA_VBLFunc);
    irqSet(IRQ_HBLANK, NEA_HBLFunc);

    NEA_Init3D();

    // Bank B for main sprites, rest for 3D textures
    NEA_Hw2DVRAMConfig cfg = {
        .main_bg  = 0,
        .main_obj = NEA_VRAM_B,
        .sub_bg   = 0,
        .sub_obj  = 0,
    };
    NEA_Hw2DInit(&cfg);

    // Camera
    scene.camera = NEA_CameraCreate();
    NEA_CameraSet(scene.camera,
                  0, 0, 4,
                  0, 0, 0,
                  0, 1, 0);

    NEA_LightSet(0, NEA_White, 0, -1, -1);
    // Alpha=0 so 3D clear is transparent — sprites behind BG0 stay visible
    NEA_ClearColorSet(RGB15(2, 2, 6), 0, 63);

    // Load the statue sprite palette (256-color, grit-converted)
    NEA_Hw2DOBJLoadPalette(NEA_ENGINE_MAIN, statuePal, 256, 0);

    // Create 3 statue sprites at different positions
    NEA_Hw2DOBJ *sprites[NUM_SPRITES];
    int sprite_x[NUM_SPRITES] = { 30, 128, 190 };
    int sprite_y[NUM_SPRITES] = { 60, 20,  80 };

    for (int i = 0; i < NUM_SPRITES; i++)
    {
        sprites[i] = NEA_Hw2DOBJCreate(NEA_ENGINE_MAIN,
                                         NEA_OBJ_SIZE_64x64,
                                         NEA_OBJ_COLOR_256);

        // Load grit-converted tile data (proper 8x8 tiled format)
        NEA_Hw2DOBJLoadGfx(sprites[i], statueTiles, statueTilesLen);

        NEA_Hw2DOBJSetPos(sprites[i], sprite_x[i], sprite_y[i]);
        NEA_Hw2DOBJSetVisible(sprites[i], true);
        NEA_Hw2DOBJSetPriority(sprites[i], 0);
    }

    // Console on sub screen
    consoleDemoInit();
    printf("NEA Hw2D Sprites Demo\n");
    printf("---------------------\n");
    printf("L/R: select sprite\n");
    printf("D-pad: move sprite\n");
    printf("A/B: flip sprite\n");
    printf("X/Y: change priority\n");

    int sel = 0; // Currently selected sprite

    while (1)
    {
        NEA_WaitForVBL(NEA_UPDATE_HW2D);

        scanKeys();
        uint32_t keys = keysHeld();
        uint32_t down = keysDown();

        // Select sprite with L/R
        if (down & KEY_R)
        {
            sel++;
            if (sel >= NUM_SPRITES)
                sel = 0;
        }
        if (down & KEY_L)
        {
            sel--;
            if (sel < 0)
                sel = NUM_SPRITES - 1;
        }

        // Move selected sprite with D-pad
        if (keys & KEY_RIGHT) sprite_x[sel] += 2;
        if (keys & KEY_LEFT)  sprite_x[sel] -= 2;
        if (keys & KEY_DOWN)  sprite_y[sel] += 2;
        if (keys & KEY_UP)    sprite_y[sel] -= 2;

        NEA_Hw2DOBJSetPos(sprites[sel], sprite_x[sel], sprite_y[sel]);

        // Toggle flip with A/B
        if (down & KEY_A)
        {
            sprites[sel]->hflip = !sprites[sel]->hflip;
            NEA_Hw2DOBJSetFlip(sprites[sel],
                                sprites[sel]->hflip, sprites[sel]->vflip);
        }
        if (down & KEY_B)
        {
            sprites[sel]->vflip = !sprites[sel]->vflip;
            NEA_Hw2DOBJSetFlip(sprites[sel],
                                sprites[sel]->hflip, sprites[sel]->vflip);
        }

        // Cycle sprite priority with X/Y (0-3)
        if (down & KEY_X)
        {
            int pri = (sprites[sel]->priority + 1) & 3;
            NEA_Hw2DOBJSetPriority(sprites[sel], pri);
        }
        if (down & KEY_Y)
        {
            int pri = (sprites[sel]->priority - 1) & 3;
            NEA_Hw2DOBJSetPriority(sprites[sel], pri);
        }

        printf("\x1b[7;0HSelected: %d        \n", sel);
        printf("Pos: %d, %d        \n", sprite_x[sel], sprite_y[sel]);
        printf("Priority: %d        \n", sprites[sel]->priority);

        NEA_ProcessArg(Draw3DScene, &scene);
    }

    return 0;
}
