#!/usr/bin/env python3
# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Warioware64, 2026
#
# Writes the example's dictionary as text, which pattern_import.py then turns
# into the .neaptn the ROM loads.
#
# The shapes are generated rather than drawn in the editor so the example
# carries no artwork anybody has to maintain, and so the set can be widened by
# editing arithmetic instead of by redrawing every digit. Two of them are
# chosen to make a point rather than to be useful: T and + have the same
# stroke directions in the same order and differ only in where the strokes
# cross, which is exactly the distinction the Light algorithm throws away.

import math

SIZE = 64

KIND_DIGIT = 1
KIND_GESTURE = 2


def arc(cx, cy, rx, ry, a0, a1, steps=12):
    """Points along an ellipse arc. Angles in degrees, y down."""
    out = []
    for i in range(steps + 1):
        t = math.radians(a0 + (a1 - a0) * i / steps)
        out.append((round(cx + rx * math.cos(t)), round(cy + ry * math.sin(t))))
    return out


def line(x0, y0, x1, y1, steps=4):
    return [(round(x0 + (x1 - x0) * i / steps),
             round(y0 + (y1 - y0) * i / steps)) for i in range(steps + 1)]


def poly(*pts):
    """A polyline through the corners, sampled so a resampler has work to do."""
    out = []
    for i in range(len(pts) - 1):
        seg = line(pts[i][0], pts[i][1], pts[i + 1][0], pts[i + 1][1])
        out.extend(seg if i == 0 else seg[1:])
    return out


def dedup(stroke):
    out = []
    for p in stroke:
        if not out or out[-1] != p:
            out.append(p)
    return out


def clamp(stroke):
    return [(min(max(x, 0), SIZE - 1), min(max(y, 0), SIZE - 1))
            for x, y in stroke]


PATTERNS = [
    # Digits. Drawn the way a right hand normally draws them, because stroke
    # direction is part of what is matched -- a 0 drawn clockwise will not
    # match one drawn anticlockwise, and that is the intended behaviour.
    ("0", KIND_DIGIT, [arc(32, 32, 20, 30, -90, 270, 20)]),
    ("1", KIND_DIGIT, [poly((32, 3), (32, 60))]),
    ("1", KIND_DIGIT, [poly((20, 12), (32, 3), (32, 60))]),
    ("2", KIND_DIGIT, [arc(32, 18, 17, 15, 204, 387, 10) + poly((48, 25), (8, 60), (56, 60))[1:]]),
    ("3", KIND_DIGIT, [arc(32, 15, 16, 14, 204, 450, 10) + arc(32, 44, 18, 16, 270, 503, 12)]),
    ("4", KIND_DIGIT, [poly((40, 3), (6, 42), (58, 42)), poly((40, 20), (40, 60))]),
    ("5", KIND_DIGIT, [poly((52, 4), (18, 4), (13, 31)) + arc(30, 44, 19, 17, 209, 491, 12)]),
    ("6", KIND_DIGIT, [poly((48, 5), (14, 34)) + arc(30, 45, 17, 16, 214, 574, 14)]),
    ("7", KIND_DIGIT, [poly((6, 5), (56, 5), (24, 60))]),
    ("8", KIND_DIGIT, [arc(32, 16, 15, 14, -90, 270, 12) + arc(32, 45, 19, 17, 270, -90, 14)]),
    ("9", KIND_DIGIT, [arc(36, 18, 16, 15, 0, 360, 12) + poly((52, 18), (30, 60))[1:]]),

    # Gestures. These are what a game would actually bind to a command.
    ("up", KIND_GESTURE, [poly((6, 52), (32, 6), (58, 52))]),
    ("down", KIND_GESTURE, [poly((6, 12), (32, 58), (58, 12))]),
    ("left", KIND_GESTURE, [poly((52, 6), (6, 32), (52, 58))]),
    ("right", KIND_GESTURE, [poly((12, 6), (58, 32), (12, 58))]),
    ("check", KIND_GESTURE, [poly((6, 34), (24, 56), (58, 6))]),
    ("loop", KIND_GESTURE, [arc(32, 32, 26, 26, 90, 450, 20)]),

    # The pair the example exists to show off. Same two stroke directions, in
    # the same order; only the crossing point differs.
    ("T", KIND_GESTURE, [poly((4, 8), (60, 8)), poly((32, 8), (32, 60))]),
    ("+", KIND_GESTURE, [poly((4, 32), (60, 32)), poly((32, 4), (32, 60))]),
    ("X", KIND_GESTURE, [poly((5, 5), (59, 59)), poly((59, 5), (5, 59))]),
]


def main():
    lines = [
        "# The dictionary the pattern_recognition example recognises against.",
        "# Generated by graphics/make_patterns.py -- edit that, not this.",
        "#",
        '# Syntax: "NAME" KIND CORRECTION SIZE | x,y x,y | x,y x,y |',
        "# Kind 1 is a digit, kind 2 is a gesture. Lines sharing a name share",
        "# a code, which is how a shape gets one prototype per way of drawing",
        "# it -- see the two entries for 1 and for 5.",
        "",
    ]

    for name, kind, strokes in PATTERNS:
        parts = []
        for stroke in strokes:
            stroke = dedup(clamp(stroke))
            assert len(stroke) >= 2, name
            parts.append(" ".join("%d,%d" % p for p in stroke))
        lines.append('"%s" %d 0 %d | %s |' % (name, kind, SIZE, " | ".join(parts)))

    with open("graphics/patterns.txt", "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print("wrote graphics/patterns.txt, %d prototypes" % len(PATTERNS))


if __name__ == "__main__":
    main()
