// SPDX-License-Identifier: CC0-1.0
//
// SPDX-FileContributor: Warioware64, 2026
//
// This file is part of Nitro Engine Advanced

#include <NEAMain.h>

// Static mesh
#include "cube_bin.h"

// Textures (generated from PNG by GRIT)
#include "brick_wall.h"
#include "a3pal32.h"
#include "concrete_bare.h"
#include "texture.h"

// Animated material data (generated by gen_animmat.py)
#include "alpha_pulse_bin.h"
#include "mat_cycle_bin.h"
#include "light_strobe_bin.h"
#include "tex_scroll_bin.h"

typedef struct {
    NEA_Camera *Camera;
    NEA_Model *Cube[4];
    NEA_AnimMatInstance *AnimMat[4];
} SceneData;

void Draw3DScene(void *arg)
{
    SceneData *Scene = arg;

    NEA_CameraUse(Scene->Camera);

    // Cube 0: alpha pulse (brick wall)
    NEA_PolyFormat(31, 0, NEA_LIGHT_0, NEA_CULL_BACK, 0);
    NEA_AnimMatApply(Scene->AnimMat[0]);
    NEA_ModelDraw(Scene->Cube[0]);

    // Cube 1: material swap (a3pal32 tinted red/green/blue)
    NEA_PolyFormat(31, 1, NEA_LIGHT_0, NEA_CULL_BACK, 0);
    NEA_AnimMatApply(Scene->AnimMat[1]);
    NEA_ModelDraw(Scene->Cube[1]);

    // Cube 2: light strobe (concrete)
    NEA_PolyFormat(31, 2, NEA_LIGHT_0, NEA_CULL_BACK, 0);
    NEA_AnimMatApply(Scene->AnimMat[2]);
    NEA_ModelDraw(Scene->Cube[2]);

    // Cube 3: texture scroll (teapot)
    NEA_PolyFormat(31, 3, NEA_LIGHT_0, NEA_CULL_BACK, 0);
    NEA_AnimMatApply(Scene->AnimMat[3]);
    NEA_ModelDraw(Scene->Cube[3]);
}

int main(int argc, char *argv[])
{
    SceneData Scene = { 0 };

    irqEnable(IRQ_HBLANK);
    irqSet(IRQ_VBLANK, NEA_VBLFunc);
    irqSet(IRQ_HBLANK, NEA_HBLFunc);

    NEA_Init3D();
    NEA_TextureSystemReset(0, 0, NEA_VRAM_ABCD);
    NEA_InitConsole();

    NEA_AnimMatSystemReset(8);

    // Camera — looking slightly down at a row of 4 cubes
    Scene.Camera = NEA_CameraCreate();
    NEA_CameraSet(Scene.Camera,
                 0, 3, -8,
                 0, 0, 0,
                 0, 1, 0);

    // Setup four lights for strobe demo
    NEA_LightSet(0, NEA_White, -0.5, -0.5, -0.5);
    NEA_LightSet(1, RGB15(20, 20, 31), 0.5, -0.5, 0.5);
    NEA_LightSet(2, RGB15(31, 20, 20), 0.0, -1.0, 0.0);
    NEA_LightSet(3, RGB15(20, 31, 20), 0.0, 0.5, -0.5);

    NEA_ClearColorSet(NEA_Black, 31, 63);

    // Create 4 cubes in a row (left to right)
    for (int i = 0; i < 4; i++)
    {
        Scene.Cube[i] = NEA_ModelCreate(NEA_Static);
        NEA_ModelLoadStaticMesh(Scene.Cube[i], cube_bin);
    }

    NEA_ModelSetCoord(Scene.Cube[0], -5, 0, 0);
    NEA_ModelSetCoord(Scene.Cube[1], -2, 0, 0);
    NEA_ModelSetCoord(Scene.Cube[2],  2, 0, 0);
    NEA_ModelSetCoord(Scene.Cube[3],  5, 0, 0);

    // -- Texture: brick wall (alpha pulse cube) --
    NEA_Material *BrickMat = NEA_MaterialCreate();
    NEA_MaterialTexLoad(BrickMat, NEA_A1RGB5, 256, 256,
                       NEA_TEXGEN_TEXCOORD | NEA_TEXTURE_WRAP_S
                       | NEA_TEXTURE_WRAP_T,
                       brick_wallBitmap);
    NEA_ModelSetMaterial(Scene.Cube[0], BrickMat);

    // -- Texture: a3pal32 shared by 3 swap materials --
    // Load the texture once, then clone VRAM references into other materials.
    NEA_Palette *A3Pal = NEA_PaletteCreate();
    NEA_PaletteLoad(A3Pal, a3pal32Pal, 32, NEA_A3PAL32);

    NEA_Material *MatRed = NEA_MaterialCreate();
    NEA_MaterialSetName(MatRed, "Red");
    NEA_MaterialTexLoad(MatRed, NEA_A3PAL32, 256, 256,
                       NEA_TEXGEN_TEXCOORD | NEA_TEXTURE_WRAP_S
                       | NEA_TEXTURE_WRAP_T,
                       a3pal32Bitmap);
    NEA_MaterialSetPalette(MatRed, A3Pal);
    NEA_MaterialSetProperties(MatRed,
        RGB15(31, 0, 0), RGB15(10, 0, 0),
        RGB15(31, 31, 31), RGB15(0, 0, 0),
        false, false);

    NEA_Material *MatGreen = NEA_MaterialCreate();
    NEA_MaterialSetName(MatGreen, "Green");
    NEA_MaterialClone(MatRed, MatGreen);
    NEA_MaterialSetProperties(MatGreen,
        RGB15(0, 31, 0), RGB15(0, 10, 0),
        RGB15(31, 31, 31), RGB15(0, 0, 0),
        false, false);

    NEA_Material *MatBlue = NEA_MaterialCreate();
    NEA_MaterialSetName(MatBlue, "Blue");
    NEA_MaterialClone(MatRed, MatBlue);
    NEA_MaterialSetProperties(MatBlue,
        RGB15(0, 0, 31), RGB15(0, 0, 10),
        RGB15(31, 31, 31), RGB15(0, 0, 0),
        false, false);

    NEA_Material *MatTable[3] = { MatRed, MatGreen, MatBlue };

    // Don't call NEA_ModelSetMaterial on cube 1 — the material swap
    // AnimMat track handles it via NEA_MaterialUse in NEA_AnimMatApply.

    // -- Texture: concrete (light strobe cube) --
    NEA_Material *ConcreteMat = NEA_MaterialCreate();
    NEA_MaterialTexLoad(ConcreteMat, NEA_A1RGB5, 256, 64,
                       NEA_TEXGEN_TEXCOORD | NEA_TEXTURE_WRAP_S
                       | NEA_TEXTURE_WRAP_T,
                       concrete_bareBitmap);
    NEA_ModelSetMaterial(Scene.Cube[2], ConcreteMat);

    // -- Texture: teapot (texture scroll cube) --
    NEA_Material *TexMat = NEA_MaterialCreate();
    NEA_MaterialTexLoad(TexMat, NEA_A1RGB5, 256, 256,
                       NEA_TEXGEN_TEXCOORD | NEA_TEXTURE_WRAP_S
                       | NEA_TEXTURE_WRAP_T,
                       textureBitmap);
    NEA_ModelSetMaterial(Scene.Cube[3], TexMat);

    // Load animation data from RAM
    NEA_AnimMatData *AlphaData = NEA_AnimMatDataLoad(alpha_pulse_bin);
    NEA_AnimMatData *MatCycleData = NEA_AnimMatDataLoad(mat_cycle_bin);
    NEA_AnimMatData *StrobeData = NEA_AnimMatDataLoad(light_strobe_bin);
    NEA_AnimMatData *TexScrollData = NEA_AnimMatDataLoad(tex_scroll_bin);

    // --- Alpha pulse instance ---
    Scene.AnimMat[0] = NEA_AnimMatCreate();
    NEA_AnimMatSetData(Scene.AnimMat[0], AlphaData);
    NEA_AnimMatSetBasePolyFormat(Scene.AnimMat[0], 31, 0,
                                 NEA_LIGHT_0, NEA_CULL_BACK, 0);
    NEA_AnimMatStart(Scene.AnimMat[0], NEA_ANIM_LOOP, floattof32(0.5));

    // --- Material cycle instance ---
    Scene.AnimMat[1] = NEA_AnimMatCreate();
    NEA_AnimMatSetData(Scene.AnimMat[1], MatCycleData);
    NEA_AnimMatSetMaterialTable(Scene.AnimMat[1], MatTable, 3);
    NEA_AnimMatSetBasePolyFormat(Scene.AnimMat[1], 31, 1,
                                 NEA_LIGHT_0, NEA_CULL_BACK, 0);
    NEA_AnimMatStart(Scene.AnimMat[1], NEA_ANIM_LOOP, floattof32(0.5));

    // --- Light strobe instance ---
    Scene.AnimMat[2] = NEA_AnimMatCreate();
    NEA_AnimMatSetData(Scene.AnimMat[2], StrobeData);
    NEA_AnimMatSetBasePolyFormat(Scene.AnimMat[2], 31, 2,
                                 NEA_LIGHT_0, NEA_CULL_BACK, 0);
    NEA_AnimMatStart(Scene.AnimMat[2], NEA_ANIM_LOOP, floattof32(0.5));

    // --- Texture scroll instance ---
    Scene.AnimMat[3] = NEA_AnimMatCreate();
    NEA_AnimMatSetData(Scene.AnimMat[3], TexScrollData);
    NEA_AnimMatSetBasePolyFormat(Scene.AnimMat[3], 31, 3,
                                 NEA_LIGHT_0, NEA_CULL_BACK, 0);
    NEA_AnimMatStart(Scene.AnimMat[3], NEA_ANIM_LOOP, floattof32(0.5));

    while (1)
    {
        NEA_WaitForVBL(NEA_UPDATE_ANIM_MAT);

        scanKeys();
        uint32_t keys = keysHeld();

        // Rotate all cubes together
        if (keys & KEY_UP)
            for (int i = 0; i < 4; i++)
                NEA_ModelRotate(Scene.Cube[i], 0, 0, 2);
        if (keys & KEY_DOWN)
            for (int i = 0; i < 4; i++)
                NEA_ModelRotate(Scene.Cube[i], 0, 0, -2);
        if (keys & KEY_RIGHT)
            for (int i = 0; i < 4; i++)
                NEA_ModelRotate(Scene.Cube[i], 0, 2, 0);
        if (keys & KEY_LEFT)
            for (int i = 0; i < 4; i++)
                NEA_ModelRotate(Scene.Cube[i], 0, -2, 0);

        printf("\x1b[0;0H"
               "Animated Material Demo\n\n"
               "1: Tex scroll\n"
               "2: Light strobe\n"
               "3: Material swap\n"
               "4: Alpha pulse\n\n"
               "D-Pad: Rotate cubes\n");

        NEA_ProcessArg(Draw3DScene, &Scene);
    }

    return 0;
}
