// SPDX-License-Identifier: CC0-1.0
//
// SPDX-FileContributor: Nitro Engine Advanced Contributors, 2024
//
// This file is part of Nitro Engine Advanced

// Multi-material model example
//
// This demonstrates loading a DLMM (Display List Multi-Material) model with
// two materials ("brick" and "concrete"), each with its own texture. The
// materials are matched to submeshes automatically by name.

#include <NEAMain.h>

// Model data (DLMM format, generated by obj2dl.py --multi-material)
#include "brick_wall_small_bin.h"

// Texture data (palette256 format, generated by ptexconv)
#include "brick_wall_tex_bin.h"
#include "brick_wall_pal_bin.h"
#include "concrete_bare_tex_bin.h"
#include "concrete_bare_pal_bin.h"

typedef struct {
    NEA_Camera *Camera;
    NEA_Model *Model;
} SceneData;

void Draw3DScene(void *arg)
{
    SceneData *Scene = arg;

    NEA_CameraUse(Scene->Camera);
    NEA_ModelDraw(Scene->Model);
}

int main(int argc, char *argv[])
{
    SceneData Scene = { 0 };

    irqEnable(IRQ_HBLANK);
    irqSet(IRQ_VBLANK, NEA_VBLFunc);
    irqSet(IRQ_HBLANK, NEA_HBLFunc);

    NEA_Init3D();

    // libnds uses VRAM_C for the text console, reserve A and B only
    NEA_TextureSystemReset(0, 0, NEA_VRAM_AB);
    consoleDemoInit();

    // Create camera
    Scene.Camera = NEA_CameraCreate();
    NEA_CameraSet(Scene.Camera,
                 -1, 2, 3,   // Position
                  1, 1, 0,   // Look at
                  0, 1, 0);  // Up direction

    // Create model
    Scene.Model = NEA_ModelCreate(NEA_Static);

    // ---- Set up "brick" material ----
    NEA_Material *BrickMat = NEA_MaterialCreate();
    NEA_MaterialSetName(BrickMat, "brick");
    NEA_MaterialTexLoad(BrickMat, NEA_PAL256, 256, 256,
                       NEA_TEXGEN_TEXCOORD | NEA_TEXTURE_WRAP_S | NEA_TEXTURE_WRAP_T, brick_wall_tex_bin);

    NEA_Palette *BrickPal = NEA_PaletteCreate();
    NEA_PaletteLoadSize(BrickPal, brick_wall_pal_bin,
                       brick_wall_pal_bin_size, NEA_PAL256);
    NEA_MaterialSetPalette(BrickMat, BrickPal);

    // ---- Set up "concrete" material ----
    NEA_Material *ConcreteMat = NEA_MaterialCreate();
    NEA_MaterialSetName(ConcreteMat, "concrete");
    NEA_MaterialTexLoad(ConcreteMat, NEA_PAL256, 256, 64,
                       NEA_TEXGEN_TEXCOORD | NEA_TEXTURE_WRAP_S | NEA_TEXTURE_WRAP_T, concrete_bare_tex_bin);

    NEA_Palette *ConcretePal = NEA_PaletteCreate();
    NEA_PaletteLoadSize(ConcretePal, concrete_bare_pal_bin,
                       concrete_bare_pal_bin_size, NEA_PAL256);
    NEA_MaterialSetPalette(ConcreteMat, ConcretePal);

    // ---- Load multi-material model and auto-bind ----
    NEA_ModelLoadMultiMesh(Scene.Model, brick_wall_small_bin);
    NEA_ModelAutoBindMaterials(Scene.Model);

    // Set up a light
    NEA_LightSet(0, NEA_White, -0.5, -0.5, -0.5);

    while (1)
    {
        NEA_WaitForVBL(0);

        scanKeys();
        uint32_t keys = keysHeld();

        printf("\x1b[0;0HPad: Rotate.");
        printf("\x1b[1;0HMulti-material model demo");

        if (keys & KEY_UP)
            NEA_ModelRotate(Scene.Model, 0, 0, -2);
        if (keys & KEY_DOWN)
            NEA_ModelRotate(Scene.Model, 0, 0, 2);
        if (keys & KEY_RIGHT)
            NEA_ModelRotate(Scene.Model, 0, 2, 0);
        if (keys & KEY_LEFT)
            NEA_ModelRotate(Scene.Model, 0, -2, 0);

        NEA_ProcessArg(Draw3DScene, &Scene);
    }

    return 0;
}
