# This is a minimal makefile only used for the examples. If you want a makefile
# for your project, take one from the templates inside examples/templates.

BINDIRS	:= data

# Use NEA ARM7 binary with rigid body physics
ARM7ELF	:= $(BLOCKSDSEXT)/nitro-engine-advanced/arm7/arm7_nea.elf

include ../../Makefile.example
