// SPDX-License-Identifier: CC0-1.0
//
// SPDX-FileContributor: Warioware64, 2026
//
// This file is part of Nitro Engine Advanced
//
// Hardware 2D tiled background example
// -------------------------------------
// Shows a tiled background (forest_town) behind a 3D scene.
// Bank E (64KB) is used for main BG tiles/map.
// Banks A-D remain available for 3D textures.
// The 3D clear color has alpha=0 so the BG shows through.

#include <NEAMain.h>

// Auto-generated by grit from forest_town.png
#include "forest_town.h"

typedef struct {
    NEA_Camera *camera;
} SceneData;

void Draw3DScene(void *arg)
{
    SceneData *scene = arg;
    NEA_CameraUse(scene->camera);

    // Draw a colored triangle
    NEA_PolyFormat(31, 0, NEA_LIGHT_0, NEA_CULL_NONE, 0);

    GFX_BEGIN = GL_TRIANGLES;

    GFX_COLOR = RGB15(31, 0, 0);
    glVertex3v16(floattov16(-1.0), floattov16(-1.0), 0);

    GFX_COLOR = RGB15(0, 31, 0);
    glVertex3v16(floattov16(1.0), floattov16(-1.0), 0);

    GFX_COLOR = RGB15(0, 0, 31);
    glVertex3v16(floattov16(0.0), floattov16(1.0), 0);

    GFX_END = 0;
}

int main(int argc, char *argv[])
{
    (void)argc;
    (void)argv;

    SceneData scene = { 0 };

    irqEnable(IRQ_HBLANK);
    irqSet(IRQ_VBLANK, NEA_VBLFunc);
    irqSet(IRQ_HBLANK, NEA_HBLFunc);

    NEA_SetTexPaletteBank(NEA_VRAM_F);
    NEA_Init3D();

    // Bank E (64KB) for main BG — maps to offset 0x06000000 (base of BG VRAM)
    // so tile/map base offsets work correctly. Banks A-D stay for 3D textures.
    NEA_Hw2DVRAMConfig cfg = {
        .main_bg  = NEA_VRAM_E,
        .main_obj = 0,
        .sub_bg   = 0,
        .sub_obj  = 0,
    };
    NEA_Hw2DInit(&cfg);

    // Camera
    scene.camera = NEA_CameraCreate();
    NEA_CameraSet(scene.camera,
                  0, 0, 3,
                  0, 0, 0,
                  0, 1, 0);

    NEA_LightSet(0, NEA_White, 0, -1, -1);

    // 3D clear color with alpha=0: 3D background is transparent,
    // letting the tiled BG behind it show through.
    NEA_ClearColorSet(NEA_Black, 0, 63);

    // Create a 512x256 tiled BG on layer 1 (layer 0 = 3D)
    NEA_Hw2DBG *bg = NEA_Hw2DBGCreate(NEA_ENGINE_MAIN, 1,
                                       NEA_HW2D_BG_TILED_8BPP, 512, 256);

    // Load grit-converted tile data, map, and palette
    NEA_Hw2DBGLoadTiles(bg, forest_townTiles, forest_townTilesLen);
    NEA_Hw2DBGLoadMap(bg, forest_townMap, forest_townMapLen);
    NEA_Hw2DBGLoadPalette(bg, forest_townPal, 256, 0);

    // BG behind 3D (priority 3 = lowest)
    NEA_Hw2DBGSetPriority(bg, 3);

    // Console on sub screen
    consoleDemoInit();
    printf("NEA Hw2D Tiled BG Demo\n");
    printf("----------------------\n");
    printf("D-pad: scroll background\n");

    int scroll_x = 0, scroll_y = 0;

    while (1)
    {
        NEA_WaitForVBL(NEA_UPDATE_HW2D);

        scanKeys();
        uint32_t keys = keysHeld();

        if (keys & KEY_RIGHT) scroll_x += 1;
        if (keys & KEY_LEFT)  scroll_x -= 1;
        if (keys & KEY_DOWN)  scroll_y += 1;
        if (keys & KEY_UP)    scroll_y -= 1;

        NEA_Hw2DBGSetScroll(bg, scroll_x, scroll_y);

        printf("\x1b[5;0HScroll: %d, %d   \n", scroll_x, scroll_y);

        NEA_ProcessArg(Draw3DScene, &scene);
    }

    return 0;
}
