#!/usr/bin/env python3
# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Warioware64, 2026
#
# Generates the multi-material test model for the AnimMat v2 example.
#
# Four quads, four materials, four names. That is the whole point: a version 2
# material animation targets a material *by name*, so a model needs several
# named materials before there is anything to demonstrate. The names here match
# the targets gen_animmat.py writes, except for "still", which deliberately has
# no target so the example can show an unanimated submesh sitting next to
# animated ones.
#
# Usage:
#     python3 make_panels.py

import math
import os

from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))

# Material name -> the panel's X position. The order is the order the submeshes
# appear in the DLMM file.
PANELS = ["scroll", "pulse", "flip", "still"]

SIZE = 64


def write_model():
    obj = ["# Generated by make_panels.py",
           "mtllib panels.mtl",
           "o panels"]

    verts = []
    uvs = []
    faces = []

    for i, name in enumerate(PANELS):
        x0 = (i - 1.5) * 2.2
        x1 = x0 + 1.8
        base = len(verts)

        verts += [(x0, -0.9, 0.0), (x1, -0.9, 0.0),
                  (x1, 0.9, 0.0), (x0, 0.9, 0.0)]
        # UVs run 0..1 twice across the quad so a scrolling texture visibly
        # repeats rather than sliding off the edge.
        uvs += [(0.0, 0.0), (2.0, 0.0), (2.0, 1.0), (0.0, 1.0)]
        faces.append((name, [base + 1, base + 2, base + 3, base + 4]))

    for v in verts:
        obj.append(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}")
    for t in uvs:
        obj.append(f"vt {t[0]:.6f} {t[1]:.6f}")
    obj.append("vn 0.000000 0.000000 -1.000000")

    for name, idx in faces:
        obj.append(f"usemtl {name}")
        obj.append("f " + " ".join(f"{i}/{i}/1" for i in idx))

    with open(os.path.join(HERE, "panels.obj"), "w") as f:
        f.write("\n".join(obj) + "\n")

    mtl = ["# Generated by make_panels.py"]
    for name in PANELS:
        mtl += [f"newmtl {name}",
                "Ka 1.000000 1.000000 1.000000",
                "Kd 1.000000 1.000000 1.000000",
                "illum 1",
                f"map_Kd {name}.png",
                ""]

    with open(os.path.join(HERE, "panels.mtl"), "w") as f:
        f.write("\n".join(mtl) + "\n")


def write_textures():
    # scroll: diagonal stripes, so a UV scroll is unmistakable.
    img = Image.new("RGB", (SIZE, SIZE), (24, 30, 48))
    d = ImageDraw.Draw(img)
    for i in range(-SIZE, SIZE * 2, 12):
        d.line([(i, 0), (i + SIZE, SIZE)], fill=(90, 170, 220), width=5)
    img.save(os.path.join(HERE, "scroll.png"))

    # pulse: a flat plate. The animation tints and fades it, so the texture
    # should not compete.
    img = Image.new("RGB", (SIZE, SIZE), (210, 210, 214))
    d = ImageDraw.Draw(img)
    d.rectangle([2, 2, SIZE - 3, SIZE - 3], outline=(150, 150, 158), width=2)
    img.save(os.path.join(HERE, "pulse.png"))

    # flip: a 16 colour ramp arranged as rings, so swapping the palette
    # underneath it reads as the whole thing changing colour at once.
    img = Image.new("P", (SIZE, SIZE))
    pal = []
    for i in range(16):
        v = i * 17
        pal += [v, v, v]
    pal += [0] * (768 - len(pal))
    img.putpalette(pal)
    px = img.load()
    c = (SIZE - 1) / 2.0
    for y in range(SIZE):
        for x in range(SIZE):
            r = math.hypot(x - c, y - c) / c
            px[x, y] = min(15, int(r * 15.99))
    img.save(os.path.join(HERE, "flip.png"))

    # still: plain, and never animated.
    img = Image.new("RGB", (SIZE, SIZE), (70, 74, 82))
    d = ImageDraw.Draw(img)
    for y in range(0, SIZE, 8):
        d.line([(0, y), (SIZE, y)], fill=(96, 100, 110))
    img.save(os.path.join(HERE, "still.png"))


def main():
    write_model()
    write_textures()
    print(f"panels.obj / panels.mtl: {len(PANELS)} materials "
          f"({', '.join(PANELS)})")
    print("textures: " + ", ".join(f"{n}.png" for n in PANELS))


if __name__ == "__main__":
    main()
