// SPDX-License-Identifier: CC0-1.0
//
// SPDX-FileContributor: Antonio Niño Díaz, 2008-2024
//
// This file is part of Nitro Engine Advanced

#include <NEAMain.h>

// Files autogenerated from bin files inside of the data and graphics folders.
#include "teapot_bin.h"
#include "teapot.h"

typedef struct {
    NEA_Camera *Camera;
    NEA_Model *ModelSpecular, *ModelDiffuse;

    bool wireframe;
} SceneData;

void Draw3DScene1(void *arg)
{
    SceneData *Scene = arg;

    NEA_CameraUse(Scene->Camera);

    NEA_PolyFormat(Scene->wireframe ? 0 : 31, 0, NEA_LIGHT_ALL, NEA_CULL_BACK, 0);

    NEA_ModelDraw(Scene->ModelSpecular);

    printf("\x1b[22;0H"
           "Polygon count: %d   \n"
           "Vertex count: %d   ",
           NEA_GetPolygonCount(),
           NEA_GetVertexCount());
}

void Draw3DScene2(void *arg)
{
    SceneData *Scene = arg;

    NEA_CameraUse(Scene->Camera);

    NEA_PolyFormat(Scene->wireframe ? 0 : 31, 0, NEA_LIGHT_ALL, NEA_CULL_BACK, 0);

    NEA_ModelDraw(Scene->ModelDiffuse);
}

int main(int argc, char *argv[])
{
    SceneData Scene = { 0 };

    irqEnable(IRQ_HBLANK);
    irqSet(IRQ_VBLANK, NEA_VBLFunc);
    irqSet(IRQ_HBLANK, NEA_HBLFunc);

    NEA_InitDual3D();
    NEA_InitConsole();

    // Allocate objects
    Scene.Camera = NEA_CameraCreate();
    Scene.ModelSpecular = NEA_ModelCreate(NEA_Static);
    Scene.ModelDiffuse = NEA_ModelCreate(NEA_Static);
    NEA_Material *MaterialSpecular = NEA_MaterialCreate();
    NEA_Material *MaterialDiffuse = NEA_MaterialCreate();

    // Setup camera
    NEA_CameraSet(Scene.Camera,
                 0, 0, 3,
                 0, 0, 0,
                 0, 1, 0);

    // Load model
    NEA_ModelLoadStaticMesh(Scene.ModelSpecular, teapot_bin);
    NEA_ModelClone(Scene.ModelDiffuse, Scene.ModelSpecular);

    // Load texture and clone it. The texture coordinates of the model are
    // outside of [0.0, 1.0], so it is needed to enable wrapping.
    NEA_MaterialTexLoad(MaterialSpecular, NEA_A1RGB5, 256, 256,
                       NEA_TEXGEN_TEXCOORD | NEA_TEXTURE_WRAP_S | NEA_TEXTURE_WRAP_T,
                       teapotBitmap);
    NEA_MaterialClone(MaterialSpecular, MaterialDiffuse);

    NEA_ModelSetMaterial(Scene.ModelSpecular, MaterialSpecular);
    NEA_ModelSetMaterial(Scene.ModelDiffuse, MaterialDiffuse);

    // Set some properties to the materials

    NEA_MaterialSetProperties(MaterialSpecular,
                             RGB15(0, 0, 0),    // Diffuse
                             RGB15(0, 0, 0),    // Ambient
                             RGB15(31, 31, 31), // Specular
                             RGB15(0, 0, 0),    // Emission
                             false, true);      // Vtx color, use shininess table

    NEA_MaterialSetProperties(MaterialDiffuse,
                             RGB15(31, 31, 31), // Diffuse
                             RGB15(0, 0, 0),    // Ambient
                             RGB15(0, 0, 0),    // Specular
                             RGB15(0, 0, 0),    // Emission
                             false, false);     // Vtx color, use shininess table

    // Set light color and direction
    NEA_LightSet(0, NEA_White, 0, 1, 0);
    NEA_LightSet(1, NEA_Blue, 0, -1, 0);
    NEA_LightSet(2, NEA_Red, 1, 0, 0);
    NEA_LightSet(3, NEA_Green, -1, 0, 0);

    NEA_ShininessFunction shininess = NEA_SHININESS_CUBIC;

    while (1)
    {
        NEA_WaitForVBL(0);

        // Get keys information
        scanKeys();
        uint32_t keys = keysHeld();
        uint32_t keys_down = keysDown();

        printf("\x1b[0;0H"
               "PAD: Rotate\n"
               "A: Set wireframe mode\n"
               "L/R: Change shininess\n");

        if (keys & KEY_A)
            Scene.wireframe = true;
        else
            Scene.wireframe = false;

        // Rotate model
        if (keys & KEY_UP)
        {
            NEA_ModelRotate(Scene.ModelSpecular, -2, 0, 0);
            NEA_ModelRotate(Scene.ModelDiffuse, -2, 0, 0);
        }
        if (keys & KEY_DOWN)
        {
            NEA_ModelRotate(Scene.ModelSpecular, 2, 0, 0);
            NEA_ModelRotate(Scene.ModelDiffuse, 2, 0, 0);
        }
        if (keys & KEY_RIGHT)
        {
            NEA_ModelRotate(Scene.ModelSpecular, 0, 2, 0);
            NEA_ModelRotate(Scene.ModelDiffuse, 0, 2, 0);
        }
        if (keys & KEY_LEFT)
        {
            NEA_ModelRotate(Scene.ModelSpecular, 0, -2, 0);
            NEA_ModelRotate(Scene.ModelDiffuse, 0, -2, 0);
        }

        // Shininess table
        // ---------------

        const char *names[] = {
            [NEA_SHININESS_NONE]      = "None     ",
            [NEA_SHININESS_LINEAR]    = "Linear   ",
            [NEA_SHININESS_QUADRATIC] = "Quadratic",
            [NEA_SHININESS_CUBIC]     = "Cubic    ",
            [NEA_SHININESS_QUARTIC]   = "Quartic  "
        };
        printf("\nShininess: %s", names[shininess]);

        if (keys_down & KEY_L)
        {
            if (shininess > NEA_SHININESS_LINEAR)
                shininess--;
        }
        if (keys_down & KEY_R)
        {
            if (shininess < NEA_SHININESS_QUARTIC)
                shininess++;
        }

        NEA_ShininessTableGenerate(shininess);

        NEA_ProcessDualArg(Draw3DScene1, Draw3DScene2, &Scene, &Scene);
    }

    return 0;
}
