# This is a minimal makefile only used for the examples. If you want a makefile
# for your project, take one from the templates inside examples/templates.

BINDIRS	:= data
GFXDIRS	:= graphics

# Override to use the local nitro-engine build instead of the installed one
LIBDIRS		:= ../../.. \
		   $(BLOCKSDS)/libs/libnds

include ../../Makefile.example
