# This is a minimal makefile only used for the examples. If you want a makefile
# for your project, take one from the templates inside examples/templates.
#
# Needs libNEA.a built and installed with NEA_TEAK=1 for the DSP path:
#
#     make -f Makefile.blocksds install NEA_TEAK=1 NEA_MAXMOD=1

include ../../Makefile.example
