// SPDX-License-Identifier: CC0-1.0
//
// SPDX-FileContributor: Nitro Engine Advanced contributors, 2026
//
// This file is part of Nitro Engine Advanced

// Particle system demo (NEAParticle / NPE).
//
// Three preset effects load from NitroFS at startup. Use L/R (or LEFT/RIGHT
// on the d-pad) to switch between fire / smoke / explosion. Press A to fire
// a burst of the current effect (only meaningful for the explosion preset,
// since the other two emit continuously). The camera orbits the emitter so
// you can see particles billboard against it from every angle.
//
// The `.npe` files are generated by `examples/effects/particles/gen_npe.py`
// using `tools/npe_editor/npe_format.py`, the same module the GUI editor
// uses to write the binary format.

#include <filesystem.h>
#include <NEAMain.h>

#define EFFECT_COUNT 3

static const char *EFFECT_PATHS[EFFECT_COUNT] = {
    "fire.npe",
    "smoke.npe",
    "explosion.npe"
};

static const char *EFFECT_NAMES[EFFECT_COUNT] = {
    "Fire",
    "Smoke",
    "Explosion"
};

typedef struct {
    NEA_Camera          *Camera;
    NEA_Material        *ParticleMat;
    NEA_Palette         *ParticlePal;
    NEA_ParticleEmitter *Emitters[EFFECT_COUNT];
    int                  active;       // currently visible effect (0..2)
    int                  frame;        // for camera orbit
} SceneData;

void Draw3DScene(void *arg)
{
    SceneData *S = arg;

    // Orbit the camera around the emitter.
    int angle = (S->frame * 1) & 0x1FF;
    int32_t cx = mulf32(floattof32(3.5f), cosLerp(angle << 6));
    int32_t cz = mulf32(floattof32(3.5f), sinLerp(angle << 6));
    NEA_CameraSetI(S->Camera, cx, floattof32(1.5f), cz,
                              0, floattof32(0.4f), 0,
                              0, floattof32(1.0f), 0);
    NEA_CameraUse(S->Camera);

    // Draw a small floor reference grid so motion is easy to read.
    NEA_PolyFormat(31, 0, 0, NEA_CULL_NONE, 0);
    GFX_COLOR = RGB15(8, 12, 16);
    NEA_PolyBegin(GL_QUAD);
    NEA_PolyVertex(-2.0f, 0.0f, -2.0f);
    NEA_PolyVertex( 2.0f, 0.0f, -2.0f);
    NEA_PolyVertex( 2.0f, 0.0f,  2.0f);
    NEA_PolyVertex(-2.0f, 0.0f,  2.0f);

    // Draw only the active emitter's particles.
    NEA_ParticleEmitterDraw(S->Emitters[S->active]);
}

__attribute__((noreturn)) void WaitLoop(void)
{
    printf("Press START to exit");
    while (1) {
        swiWaitForVBlank();
        scanKeys();
        if (keysHeld() & KEY_START) exit(0);
    }
}

int main(int argc, char *argv[])
{
    SceneData Scene = { 0 };

    irqEnable(IRQ_HBLANK);
    irqSet(IRQ_VBLANK, NEA_VBLFunc);
    irqSet(IRQ_HBLANK, NEA_HBLFunc);

    consoleDemoInit();

    if (!nitroFSInit(NULL)) {
        printf("nitroFSInit() failed\n");
        WaitLoop();
    }

    NEA_Init3D();
    NEA_InitConsole();

    NEA_TextureSystemReset(0, 0, NEA_VRAM_AB);
    // Camera + particle subsystem.
    Scene.Camera = NEA_CameraCreate();
    NEA_ParticleSystemReset(8);
    NEA_ParticleSystemSetCamera(Scene.Camera);

    // Shared material + palette for all the example effects. Naming it
    // "particle" lets the .npe files look it up via NEA_MaterialFindByName()
    // -- no explicit NEA_ParticleEmitterSetMaterial() needed.
    Scene.ParticleMat = NEA_MaterialCreate();
    Scene.ParticlePal = NEA_PaletteCreate();
    NEA_MaterialSetName(Scene.ParticleMat, "particle");
    if (NEA_MaterialTexLoadGRF(Scene.ParticleMat, Scene.ParticlePal,
                               NEA_TEXGEN_TEXCOORD,
                               "particle_png.grf") == 0)
    {
        printf("Failed to load particle texture\n");
        WaitLoop();
    }

    // Load every preset. Each .npe carries "particle" as its material name,
    // so the loader auto-binds Scene.ParticleMat above.
    for (int i = 0; i < EFFECT_COUNT; i++) {
        Scene.Emitters[i] = NEA_ParticleEmitterCreate();
        if (!NEA_ParticleEmitterLoadFAT(Scene.Emitters[i], EFFECT_PATHS[i])) {
            printf("Failed to load %s\n", EFFECT_PATHS[i]);
            WaitLoop();
        }
        NEA_ParticleEmitterSetPosition(Scene.Emitters[i], 0, 0, 0);
    }

    Scene.active = 0;
    NEA_ParticleEmitterPlay(Scene.Emitters[0]);

    while (1) {
        // NEA_UPDATE_PARTICLES advances every emitter once per frame.
        NEA_WaitForVBL(NEA_UPDATE_PARTICLES);

        scanKeys();
        uint32_t down = keysDown();

        if (down & (KEY_R | KEY_RIGHT)) {
            NEA_ParticleEmitterStop(Scene.Emitters[Scene.active]);
            Scene.active = (Scene.active + 1) % EFFECT_COUNT;
            NEA_ParticleEmitterPlay(Scene.Emitters[Scene.active]);
        }
        if (down & (KEY_L | KEY_LEFT)) {
            NEA_ParticleEmitterStop(Scene.Emitters[Scene.active]);
            Scene.active = (Scene.active + EFFECT_COUNT - 1) % EFFECT_COUNT;
            NEA_ParticleEmitterPlay(Scene.Emitters[Scene.active]);
        }
        if (down & KEY_A) {
            // Fire a burst of the active effect's burst_count (set in the
            // NPE file). Useful especially for explosion-style presets.
            NEA_ParticleEmitterEmitBurst(Scene.Emitters[Scene.active], 64);
        }

        NEA_ProcessArg(Draw3DScene, &Scene);
        Scene.frame++;

        consoleClear();
        printf("NEA particles demo\n");
        printf("==================\n\n");
        printf("Effect: %s  (%d/%d)\n",
               EFFECT_NAMES[Scene.active], Scene.active + 1, EFFECT_COUNT);
        printf("Alive:  %d\n\n",
               NEA_ParticleEmitterAliveCount(Scene.Emitters[Scene.active]));
        printf("L/R: switch effect\n");
        printf("A:   burst\n");
    }

    return 0;
}
