#!/usr/bin/env python3
# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Warioware64, 2026
#
# Generates a smooth-weighted MD5 test asset for the NSMW skinning path.
#
# Every skinned asset that shipped with Nitro Engine Advanced is rigidly
# weighted -- Robot.md5mesh has one weight on all 576 of its vertices -- so the
# two-weight path that NSMW exists for was never exercised by anything in the
# tree. That matters, because NSMW spends one matrix-stack slot per distinct
# (joint pair, weight) combination and there are only 30 of them. A rigid mesh
# uses one slot per bone and never comes close; a smoothly weighted one can want
# hundreds.
#
# This builds the smallest thing that has that property: a tentacle. A chain of
# bones inside a cylinder, with each vertex blended between the two bones it
# lies between, and the blend varying around the circumference as well as along
# the length the way a real limb's weights do.
#
# Usage:
#     python3 make_tentacle.py

import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))

NUM_BONES = 12      # chain length
SEG_LEN = 0.55      # distance between bones (the whole chain must fit the
                    # v16 vertex range, which is +/-8 world units)
RINGS = 40          # vertex rings along the tentacle
SEGMENTS = 10       # vertices around each ring
RADIUS_BASE = 0.65
RADIUS_TIP = 0.18
NUM_FRAMES = 32
FRAME_RATE = 24

LENGTH = SEG_LEN * (NUM_BONES - 1)


def fmt(v):
    return f"{v:.10f}"


def quat_x(angle):
    """Rotation about X, in the (x, y, z) form MD5 stores.

    MD5 leaves w out and the reader recomputes it as -sqrt(1 - x^2 - y^2 - z^2),
    so the stored components must be the half of the pair whose w is negative.
    """
    w = math.cos(angle / 2.0)
    x = math.sin(angle / 2.0)
    if w > 0.0:          # q and -q are the same rotation; keep the w <= 0 one
        w, x = -w, -x
    return (x, 0.0, 0.0)


def bone_z(i):
    return i * SEG_LEN


def vertex_weights(z, theta):
    """Which two bones a point belongs to, and how much of each.

    The blend follows the point's position along the chain, plus a small term
    that varies around the circumference. That second term is what makes the
    weights genuinely per-vertex rather than per-ring -- which is the whole
    point of the asset, since per-ring weights would collapse to a handful of
    distinct combinations and never stress the node budget.
    """
    t = max(0.0, min(1.0, z / LENGTH)) * (NUM_BONES - 1)
    lo = min(int(t), NUM_BONES - 2)
    blend = t - lo

    blend += 0.09 * math.sin(theta * 2.0 + lo * 0.7)
    blend = max(0.0, min(1.0, blend))

    return lo, lo + 1, 1.0 - blend, blend


def build():
    verts = []      # (u, v, first_weight, weight_count)
    weights = []    # (joint, bias, x, y, z)
    tris = []

    for r in range(RINGS):
        fz = r / (RINGS - 1)
        z = fz * LENGTH
        radius = RADIUS_BASE + (RADIUS_TIP - RADIUS_BASE) * fz

        for s in range(SEGMENTS):
            theta = 2.0 * math.pi * s / SEGMENTS
            x = math.cos(theta) * radius
            y = math.sin(theta) * radius

            j0, j1, w0, w1 = vertex_weights(z, theta)

            first = len(weights)
            # Bone rest orientations are identity, so a point's position in a
            # joint's space is just the offset from that joint.
            weights.append((j0, w0, x, y, z - bone_z(j0)))
            weights.append((j1, w1, x, y, z - bone_z(j1)))

            verts.append((s / SEGMENTS, fz, first, 2))

    for r in range(RINGS - 1):
        for s in range(SEGMENTS):
            s2 = (s + 1) % SEGMENTS
            a = r * SEGMENTS + s
            b = r * SEGMENTS + s2
            c = (r + 1) * SEGMENTS + s
            d = (r + 1) * SEGMENTS + s2
            tris.append((a, c, b))
            tris.append((b, c, d))

    return verts, weights, tris


def write_mesh(path, verts, weights, tris):
    out = []
    out.append("MD5Version 10 // Generated by make_tentacle.py")
    out.append('commandline ""')
    out.append("")
    out.append(f"numJoints {NUM_BONES}")
    out.append("numMeshes 1")
    out.append("")
    out.append("joints {")
    for i in range(NUM_BONES):
        parent = i - 1
        out.append(f'  "Bone{i:02d}" {parent} '
                   f"( {fmt(0.0)} {fmt(0.0)} {fmt(bone_z(i))} ) "
                   f"( {fmt(0.0)} {fmt(0.0)} {fmt(0.0)} )")
    out.append("}")
    out.append("")
    out.append("mesh {")
    out.append('  shader "tentacle"')
    out.append("")
    out.append(f"  numverts {len(verts)}")
    for i, (u, v, first, count) in enumerate(verts):
        out.append(f"  vert {i} ( {fmt(u)} {fmt(v)} ) {first} {count}")
    out.append("")
    out.append(f"  numtris {len(tris)}")
    for i, (a, b, c) in enumerate(tris):
        out.append(f"  tri {i} {a} {b} {c}")
    out.append("")
    out.append(f"  numweights {len(weights)}")
    for i, (j, bias, x, y, z) in enumerate(weights):
        out.append(f"  weight {i} {j} {fmt(bias)} "
                   f"( {fmt(x)} {fmt(y)} {fmt(z)} )")
    out.append("}")
    out.append("")

    with open(path, "w") as f:
        f.write("\n".join(out))


def write_anim(path):
    out = []
    out.append("MD5Version 10 // Generated by make_tentacle.py")
    out.append('commandline ""')
    out.append("")
    out.append(f"numFrames {NUM_FRAMES}")
    out.append(f"numJoints {NUM_BONES}")
    out.append(f"frameRate {FRAME_RATE}")
    out.append(f"numAnimatedComponents {NUM_BONES * 6}")
    out.append("")
    out.append("hierarchy {")
    for i in range(NUM_BONES):
        out.append(f'  "Bone{i:02d}" {i - 1} 63 {i * 6} //')
    out.append("}")
    out.append("")

    # A generous fixed box. Nothing in the NEA pipeline reads these, but the
    # format requires one per frame.
    out.append("bounds {")
    for _ in range(NUM_FRAMES):
        out.append(f"  ( {fmt(-3.0)} {fmt(-3.0)} {fmt(-1.0)} ) "
                   f"( {fmt(3.0)} {fmt(3.0)} {fmt(LENGTH + 2.0)} )")
    out.append("}")
    out.append("")

    out.append("baseframe {")
    for i in range(NUM_BONES):
        z = 0.0 if i == 0 else SEG_LEN
        out.append(f"  ( {fmt(0.0)} {fmt(0.0)} {fmt(z)} ) "
                   f"( {fmt(0.0)} {fmt(0.0)} {fmt(0.0)} )")
    out.append("}")
    out.append("")

    for f_i in range(NUM_FRAMES):
        phase = 2.0 * math.pi * f_i / NUM_FRAMES
        out.append(f"frame {f_i} {{")
        for i in range(NUM_BONES):
            z = 0.0 if i == 0 else SEG_LEN
            # A travelling wave down the chain, so consecutive bones disagree
            # and the smooth weights actually have something to smooth.
            angle = 0.0 if i == 0 else 0.30 * math.sin(phase - i * 0.55)
            qx, qy, qz = quat_x(angle)
            out.append(f"  {fmt(0.0)} {fmt(0.0)} {fmt(z)} "
                       f"{fmt(qx)} {fmt(qy)} {fmt(qz)}")
        out.append("}")
        out.append("")

    with open(path, "w") as f:
        f.write("\n".join(out))


def main():
    verts, weights, tris = build()

    write_mesh(os.path.join(HERE, "Tentacle.md5mesh"), verts, weights, tris)
    write_anim(os.path.join(HERE, "Wave.md5anim"))

    print(f"Tentacle.md5mesh: {NUM_BONES} bones, {len(verts)} verts, "
          f"{len(tris)} tris, {len(weights)} weights (2 per vertex)")
    print(f"Wave.md5anim:     {NUM_FRAMES} frames")


if __name__ == "__main__":
    main()
