// SPDX-License-Identifier: MIT
//
// Copyright (c) 2026 Warioware64
//
// This file is part of Nitro Engine Advanced
//
// Cell animation: loading, playback and the evaluator the three backends
// share. The drawing lives elsewhere -- NEACellDraw.c for the 3D quads and
// billboards, NEACellOAM.c for the hardware OBJ path, which is a separate
// translation unit so a ROM that never binds OAM does not link NEAHw2D.
//
// tools/cell_editor/cell_format.py writes the layout this reads and mirrors
// the evaluator below function for function; tests/cell_eval checks that they
// still agree. If you change one, change the other.

#include <stdlib.h>
#include <string.h>

#include "NEAMain.h"

#include "NEACellSin.h"

//-----------------------------------------------------------------------------
// System state
//-----------------------------------------------------------------------------

static NEA_CellAnim **ne_cell_anims = NULL;
static int ne_cell_max_anims = 0;
static bool ne_cell_system_inited = false;

NEA_Camera *__ne_cell_camera = NULL;

//-----------------------------------------------------------------------------
// Section tags. Four ASCII bytes in file order, so 'A','T','L','S' on disk
// reads back as this u32 on a little-endian machine.
//-----------------------------------------------------------------------------

#define NE_TAG(a, b, c, d) \
    ((uint32_t)(a) | ((uint32_t)(b) << 8) | ((uint32_t)(c) << 16) \
     | ((uint32_t)(d) << 24))

#define TAG_ATLS NE_TAG('A', 'T', 'L', 'S')
#define TAG_CELS NE_TAG('C', 'E', 'L', 'S')
#define TAG_PART NE_TAG('P', 'A', 'R', 'T')
#define TAG_SEQS NE_TAG('S', 'E', 'Q', 'S')
#define TAG_FRMS NE_TAG('F', 'R', 'M', 'S')
#define TAG_TRKS NE_TAG('T', 'R', 'K', 'S')
#define TAG_KEYS NE_TAG('K', 'E', 'Y', 'S')
#define TAG_MCEL NE_TAG('M', 'C', 'E', 'L')
#define TAG_NODE NE_TAG('N', 'O', 'D', 'E')
#define TAG_BUDG NE_TAG('B', 'U', 'D', 'G')

typedef struct {
    uint32_t magic;
    uint16_t version;
    uint16_t flags;
    uint16_t num_sections;
    uint16_t reserved;
    uint32_t file_size;
} ne_cell_header_t;

typedef struct {
    uint32_t tag;
    uint32_t offset;
} ne_cell_section_t;

//-----------------------------------------------------------------------------
// Fixed point and trigonometry
//
// The angle unit is the file's: 65536 is a full turn, which is retail NANR's
// unit. The table is generated by cell_format.py so the preview in the editor
// and the ARM9 produce the same integers; libnds sinLerp() is deliberately not
// used, because its table is inside libnds.a and nothing on the host can
// mirror it without guessing.
//-----------------------------------------------------------------------------

#define NE_SIN_SHIFT 7
#define NE_SIN_SIZE  512

ARM_CODE static inline int32_t ne_cell_sin(uint32_t rot)
{
    rot &= 0xFFFF;
    uint32_t idx = rot >> NE_SIN_SHIFT;
    uint32_t frac = rot & ((1 << NE_SIN_SHIFT) - 1);
    int32_t a = ne_cell_sin_table[idx];
    int32_t b = ne_cell_sin_table[(idx + 1) & (NE_SIN_SIZE - 1)];
    return a + (((b - a) * (int32_t)frac) >> NE_SIN_SHIFT);
}

ARM_CODE static inline int32_t ne_cell_cos(uint32_t rot)
{
    return ne_cell_sin(rot + (NEA_CELL_ROT_FULL / 4));
}

// Exposed only so tests/cell_eval can compare this table against the one
// cell_format.py generated. Nothing else should reach for it: the table is an
// implementation detail of the evaluator.
const int16_t *__NEA_CellSinTable(void)
{
    return ne_cell_sin_table;
}

//-----------------------------------------------------------------------------
// Affine helpers. An xform is a 2x2 matrix plus a translation, all f32; it
// maps a point p to m * p + t.
//-----------------------------------------------------------------------------

typedef struct {
    int32_t m[4];
    int32_t tx, ty;
} ne_xform_t;

static const ne_xform_t NE_XFORM_IDENTITY = {
    { 1 << 12, 0, 0, 1 << 12 }, 0, 0
};

ARM_CODE static inline void ne_xform_apply(const ne_xform_t *x,
                                           int32_t px, int32_t py,
                                           int32_t *ox, int32_t *oy)
{
    *ox = mulf32(x->m[0], px) + mulf32(x->m[1], py) + x->tx;
    *oy = mulf32(x->m[2], px) + mulf32(x->m[3], py) + x->ty;
}

// The map that applies `inner` first, then `outer`.
ARM_CODE static void ne_xform_compose(const ne_xform_t *outer,
                                      const ne_xform_t *inner,
                                      ne_xform_t *out)
{
    ne_xform_t r;
    r.m[0] = mulf32(outer->m[0], inner->m[0]) + mulf32(outer->m[1], inner->m[2]);
    r.m[1] = mulf32(outer->m[0], inner->m[1]) + mulf32(outer->m[1], inner->m[3]);
    r.m[2] = mulf32(outer->m[2], inner->m[0]) + mulf32(outer->m[3], inner->m[2]);
    r.m[3] = mulf32(outer->m[2], inner->m[1]) + mulf32(outer->m[3], inner->m[3]);
    ne_xform_apply(outer, inner->tx, inner->ty, &r.tx, &r.ty);
    *out = r;
}

// Scale, then rotate, then translate, about (cx, cy).
//
// This is NitroPaint's AnmCalcTransformMatrix written as an affine map, so a
// frame imported from a retail NANR lands exactly where the original runtime
// put it.
ARM_CODE static void ne_xform_srt(uint32_t rot, int32_t sx, int32_t sy,
                                  int32_t cx, int32_t cy,
                                  int32_t tx, int32_t ty, ne_xform_t *out)
{
    if (rot & 0xFFFF)
    {
        int32_t s = ne_cell_sin(rot);
        int32_t c = ne_cell_cos(rot);
        out->m[0] = mulf32(sx, c);
        out->m[1] = -mulf32(sy, s);
        out->m[2] = mulf32(sx, s);
        out->m[3] = mulf32(sy, c);
    }
    else
    {
        out->m[0] = sx;
        out->m[1] = 0;
        out->m[2] = 0;
        out->m[3] = sy;
    }

    int32_t mx = mulf32(out->m[0], cx) + mulf32(out->m[1], cy);
    int32_t my = mulf32(out->m[2], cx) + mulf32(out->m[3], cy);
    out->tx = cx - mx + tx;
    out->ty = cy - my + ty;
}

//-----------------------------------------------------------------------------
// Loading
//-----------------------------------------------------------------------------

static const void *ne_cell_find_section(const uint8_t *base,
                                        const ne_cell_header_t *hdr,
                                        uint32_t tag, uint32_t *count)
{
    const ne_cell_section_t *dir =
        (const ne_cell_section_t *)(base + sizeof(ne_cell_header_t));

    for (int i = 0; i < hdr->num_sections; i++)
    {
        if (dir[i].tag != tag)
            continue;
        if (dir[i].offset + 4 > hdr->file_size)
            return NULL;
        const uint8_t *payload = base + dir[i].offset;
        if (count)
            *count = *(const uint32_t *)payload;
        return payload + 4;
    }

    if (count)
        *count = 0;
    return NULL;
}

// The frame lookup is a binary search over per-sequence prefix sums of the
// frame durations. Building them here costs one pass at load; not building
// them would cost a walk of the frame list on every evaluation of every
// instance, which is the one part of this that runs 60 times a second.
static bool ne_cell_build_prefix(NEA_CellData *data)
{
    uint32_t total = 0;
    for (int i = 0; i < data->num_sequences; i++)
        total += (uint32_t)data->sequences[i].num_frames + 1;

    if (total == 0)
        return true;

    data->seq_prefix = calloc(total, sizeof(uint16_t));
    data->seq_prefix_base = calloc(data->num_sequences, sizeof(uint16_t));
    if (data->seq_prefix == NULL || data->seq_prefix_base == NULL)
        return false;

    uint32_t at = 0;
    for (int i = 0; i < data->num_sequences; i++)
    {
        const NEA_CellSequence *seq = &data->sequences[i];
        data->seq_prefix_base[i] = at;
        uint16_t acc = 0;
        data->seq_prefix[at++] = 0;
        for (int f = 0; f < seq->num_frames; f++)
        {
            uint16_t dur = data->frames[seq->first_frame + f].duration;
            acc += dur ? dur : 1;
            data->seq_prefix[at++] = acc;
        }
    }
    return true;
}

// A child part reads its parent's finished transform straight out of the
// scratch array, which only works if parents come first. Rejecting a file that
// breaks that here means the evaluator never has to check.
static bool ne_cell_validate(const NEA_CellData *data)
{
    for (int c = 0; c < data->num_cells; c++)
    {
        const NEA_CellCell *cell = &data->cells[c];
        if ((uint32_t)cell->first_part + cell->num_parts > data->num_parts)
        {
            NEA_DebugPrint("NEACell: cell %d runs past the part pool", c);
            return false;
        }
        for (int p = 0; p < cell->num_parts; p++)
        {
            const NEA_CellPart *part = &data->parts[cell->first_part + p];
            if (part->parent >= p)
            {
                NEA_DebugPrint("NEACell: cell %d part %d parents forward", c, p);
                return false;
            }
            if (part->atlas >= data->num_atlases)
            {
                NEA_DebugPrint("NEACell: cell %d part %d: bad atlas", c, p);
                return false;
            }
        }
    }

    for (int s = 0; s < data->num_sequences; s++)
    {
        const NEA_CellSequence *seq = &data->sequences[s];
        if ((uint32_t)seq->first_frame + seq->num_frames > data->num_frames)
        {
            NEA_DebugPrint("NEACell: sequence %d runs past the frame pool", s);
            return false;
        }
        if ((uint32_t)seq->first_track + seq->num_tracks > data->num_tracks)
        {
            NEA_DebugPrint("NEACell: sequence %d runs past the track pool", s);
            return false;
        }
        if (seq->kind == NEA_CELL_KIND_RIG && seq->cell >= data->num_cells)
        {
            NEA_DebugPrint("NEACell: sequence %d: bad rig cell", s);
            return false;
        }
    }

    return true;
}

NEA_CellData *NEA_CellDataLoad(const void *pointer)
{
    NEA_AssertPointer(pointer, "NULL pointer");

    const uint8_t *base = pointer;
    const ne_cell_header_t *hdr = pointer;

    if (hdr->magic != NEA_CELL_MAGIC)
    {
        NEA_DebugPrint("NEACell: bad magic 0x%08lX", (unsigned long)hdr->magic);
        return NULL;
    }
    if (hdr->version != NEA_CELL_VERSION)
    {
        NEA_DebugPrint("NEACell: unsupported version %d", hdr->version);
        return NULL;
    }

    NEA_CellData *data = calloc(1, sizeof(NEA_CellData));
    if (data == NULL)
    {
        NEA_DebugPrint("NEACell: not enough memory");
        return NULL;
    }

    data->flags = hdr->flags;

    uint32_t count = 0;
    data->atlases = ne_cell_find_section(base, hdr, TAG_ATLS, &count);
    data->num_atlases = count;
    data->cells = ne_cell_find_section(base, hdr, TAG_CELS, &count);
    data->num_cells = count;
    data->parts = ne_cell_find_section(base, hdr, TAG_PART, &count);
    data->num_parts = count;
    data->sequences = ne_cell_find_section(base, hdr, TAG_SEQS, &count);
    data->num_sequences = count;
    data->frames = ne_cell_find_section(base, hdr, TAG_FRMS, &count);
    data->num_frames = count;
    data->tracks = ne_cell_find_section(base, hdr, TAG_TRKS, &count);
    data->num_tracks = count;
    data->keys = ne_cell_find_section(base, hdr, TAG_KEYS, &count);
    data->multicells = ne_cell_find_section(base, hdr, TAG_MCEL, &count);
    data->num_multicells = count;
    data->nodes = ne_cell_find_section(base, hdr, TAG_NODE, &count);
    data->num_nodes = count;
    data->budget = ne_cell_find_section(base, hdr, TAG_BUDG, &count);

    if (data->cells == NULL || data->parts == NULL || data->sequences == NULL)
    {
        NEA_DebugPrint("NEACell: file is missing a required section");
        free(data);
        return NULL;
    }

    if (!ne_cell_validate(data))
    {
        free(data);
        return NULL;
    }

    for (int c = 0; c < data->num_cells; c++)
    {
        if (data->cells[c].num_parts > data->max_parts_any_cell)
            data->max_parts_any_cell = data->cells[c].num_parts;
    }

    if (data->num_atlases > 0)
    {
        data->atlas_mat = calloc(data->num_atlases, sizeof(NEA_Material *));
        if (data->atlas_mat == NULL)
        {
            free(data);
            return NULL;
        }
    }

    if (!ne_cell_build_prefix(data))
    {
        free(data->seq_prefix);
        free(data->seq_prefix_base);
        free(data->atlas_mat);
        free(data);
        return NULL;
    }

    return data;
}

NEA_CellData *NEA_CellDataLoadFAT(const char *path)
{
    NEA_AssertPointer(path, "NULL path");

    void *buffer = NEA_FATLoadData(path);
    if (buffer == NULL)
    {
        NEA_DebugPrint("NEACell: couldn't read %s", path);
        return NULL;
    }

    NEA_CellData *data = NEA_CellDataLoad(buffer);
    if (data == NULL)
    {
        free(buffer);
        return NULL;
    }

    data->_base_data = buffer;
    data->_loaded_from_fat = true;
    return data;
}

void NEA_CellDataFree(NEA_CellData *data)
{
    if (data == NULL)
        return;

    // An instance left pointing at freed data would evaluate garbage on the
    // next VBL, so cut them loose first.
    for (int i = 0; i < ne_cell_max_anims; i++)
    {
        NEA_CellAnim *anim = ne_cell_anims ? ne_cell_anims[i] : NULL;
        if (anim && anim->data == data)
        {
            NEA_CellAnimStop(anim);
            anim->data = NULL;
            anim->pose_count = 0;
        }
    }

    free(data->atlas_mat);
    free(data->seq_prefix);
    free(data->seq_prefix_base);
    if (data->_loaded_from_fat)
        free(data->_base_data);
    free(data);
}

int NEA_CellDataBindMaterials(NEA_CellData *data)
{
    NEA_AssertPointer(data, "NULL data");

    int missing = 0;
    for (int i = 0; i < data->num_atlases; i++)
    {
        NEA_Material *mat = NEA_MaterialFindByName(data->atlases[i].name);
        data->atlas_mat[i] = mat;
        if (mat == NULL)
        {
            NEA_DebugPrint("NEACell: no material named '%s'",
                           data->atlases[i].name);
            missing++;
        }
    }
    return missing;
}

int NEA_CellDataSetMaterial(NEA_CellData *data, int atlas, NEA_Material *mat)
{
    NEA_AssertPointer(data, "NULL data");
    if (atlas < 0 || atlas >= data->num_atlases)
        return -1;
    data->atlas_mat[atlas] = mat;
    return 0;
}

//-----------------------------------------------------------------------------
// Query
//-----------------------------------------------------------------------------

int NEA_CellFindSequence(const NEA_CellData *data, const char *name)
{
    NEA_AssertPointer(data, "NULL data");
    NEA_AssertPointer(name, "NULL name");

    for (int i = 0; i < data->num_sequences; i++)
    {
        if (strncmp(data->sequences[i].name, name,
                    sizeof(data->sequences[i].name)) == 0)
            return i;
    }
    return -1;
}

int NEA_CellFindMultiCell(const NEA_CellData *data, const char *name)
{
    NEA_AssertPointer(data, "NULL data");
    NEA_AssertPointer(name, "NULL name");

    for (int i = 0; i < data->num_multicells; i++)
    {
        if (strncmp(data->multicells[i].name, name,
                    sizeof(data->multicells[i].name)) == 0)
            return i;
    }
    return -1;
}

int NEA_CellSequenceTicks(const NEA_CellData *data, int seq)
{
    NEA_AssertPointer(data, "NULL data");
    if (seq < 0 || seq >= data->num_sequences)
        return 0;
    int ticks = data->sequences[seq].total_ticks;
    return ticks > 0 ? ticks : 1;
}

int NEA_CellGetBounds(const NEA_CellData *data, int cell,
                      int *min_x, int *min_y, int *max_x, int *max_y)
{
    NEA_AssertPointer(data, "NULL data");
    if (cell < 0 || cell >= data->num_cells)
        return -1;

    const NEA_CellCell *c = &data->cells[cell];
    if (min_x)
        *min_x = c->min_x;
    if (min_y)
        *min_y = c->min_y;
    if (max_x)
        *max_x = c->max_x;
    if (max_y)
        *max_y = c->max_y;
    return 0;
}

//-----------------------------------------------------------------------------
// The evaluator
//
// Mirrored by evaluate_track() / evaluate_sequence() in cell_format.py. The
// two are compared tick for tick by tests/cell_eval, so any change here needs
// the same change there.
//-----------------------------------------------------------------------------

// Channels stored as f32 at runtime but baked as 1.10.5.
static inline bool ne_cell_channel_is_fixed(uint8_t channel)
{
    return channel == NEA_CELL_CH_TX || channel == NEA_CELL_CH_TY
        || channel == NEA_CELL_CH_SX || channel == NEA_CELL_CH_SY;
}

ARM_CODE static inline int32_t ne_cell_widen_baked(uint8_t channel, int16_t v)
{
    if (ne_cell_channel_is_fixed(channel))
        return (int32_t)v << 7;
    return (int32_t)((uint16_t)v);
}

ARM_CODE static int32_t ne_cell_rgb15_lerp(uint32_t c0, uint32_t c1,
                                           int32_t frac)
{
    int32_t r0 = c0 & 0x1F, g0 = (c0 >> 5) & 0x1F, b0 = (c0 >> 10) & 0x1F;
    int32_t r1 = c1 & 0x1F, g1 = (c1 >> 5) & 0x1F, b1 = (c1 >> 10) & 0x1F;

    int32_t r = r0 + mulf32(r1 - r0, frac);
    int32_t g = g0 + mulf32(g1 - g0, frac);
    int32_t b = b0 + mulf32(b1 - b0, frac);

    if (r < 0) r = 0; else if (r > 31) r = 31;
    if (g < 0) g = 0; else if (g > 31) g = 31;
    if (b < 0) b = 0; else if (b > 31) b = 31;
    return r | (g << 5) | (b << 10);
}

// Shortest-arc interpolation. Without it a track running from 350 to 10
// degrees takes the long way round, which is never what was drawn.
ARM_CODE static int32_t ne_cell_rot_lerp(uint32_t a, uint32_t b, int32_t frac)
{
    a &= 0xFFFF;
    b &= 0xFFFF;
    int32_t delta = (int32_t)((b - a) & 0xFFFF);
    if (delta > 0x8000)
        delta -= 0x10000;
    return (int32_t)((a + mulf32(delta, frac)) & 0xFFFF);
}

ARM_CODE static int32_t ne_cell_eval_track(const NEA_CellData *data,
                                           const NEA_CellTrack *track,
                                           int32_t tick_f32)
{
    if (track->storage == NEA_CELL_STORE_CONST)
        return (int32_t)track->data;

    if (track->storage == NEA_CELL_STORE_BAKED)
    {
        if (track->count == 0)
            return 0;
        const int16_t *values = (const int16_t *)(data->keys + track->data);
        int i = tick_f32 >> 12;
        if (i < 0)
            i = 0;
        else if (i >= track->count)
            i = track->count - 1;
        return ne_cell_widen_baked(track->channel, values[i]);
    }

    const NEA_CellKeyframe *keys =
        (const NEA_CellKeyframe *)(data->keys + track->data);
    if (track->count == 0)
        return 0;
    if (track->count == 1)
        return keys[0].value;

    int tick = tick_f32 >> 12;
    if (tick <= keys[0].tick)
        return keys[0].value;
    if (tick >= keys[track->count - 1].tick)
        return keys[track->count - 1].value;

    int lo = 0;
    int hi = track->count - 1;
    while (lo < hi - 1)
    {
        int mid = (lo + hi) >> 1;
        if (keys[mid].tick <= tick)
            lo = mid;
        else
            hi = mid;
    }

    // These carry no meaningful midpoint, so they step whatever the track says.
    if (track->interp == NEA_CELL_INTERP_STEP
        || track->channel == NEA_CELL_CH_VISIBLE
        || track->channel == NEA_CELL_CH_PARTSWAP)
        return keys[lo].value;

    int span = keys[hi].tick - keys[lo].tick;
    if (span <= 0)
        return keys[lo].value;

    int32_t frac = divf32(tick_f32 - ((int32_t)keys[lo].tick << 12),
                          span << 12);
    if (frac < 0)
        frac = 0;
    else if (frac > (1 << 12))
        frac = 1 << 12;

    int32_t a = keys[lo].value;
    int32_t b = keys[hi].value;

    switch (track->channel)
    {
        case NEA_CELL_CH_ROT:
            return ne_cell_rot_lerp(a, b, frac);
        case NEA_CELL_CH_COLOR:
            return ne_cell_rgb15_lerp(a & 0x7FFF, b & 0x7FFF, frac);
        case NEA_CELL_CH_ALPHA:
        {
            int32_t va = a & 0x1F, vb = b & 0x1F;
            int32_t v = va + mulf32(vb - va, frac);
            if (v < 0) v = 0; else if (v > 31) v = 31;
            return v;
        }
        default:
            return a + mulf32(b - a, frac);
    }
}

// Map an ever-increasing play head onto a position inside the sequence.
//
// Stateless on purpose. Retail drives ping-pong with a direction flag the
// player mutates, which makes seeking to an arbitrary tick impossible and is
// easy for two implementations to disagree about. Mirroring the play head
// instead gives the same visible behaviour -- a frame still plays for its full
// duration in both directions -- and lets the editor and the ARM9 both answer
// "what does tick N look like?" without simulating ticks 0..N-1.
ARM_CODE static int32_t ne_cell_resolve_position(const NEA_CellSequence *seq,
                                                 int32_t total_ticks,
                                                 int32_t tick_f32,
                                                 bool *finished)
{
    int32_t total = total_ticks << 12;
    *finished = false;

    if (tick_f32 < 0)
        tick_f32 = 0;

    if (seq->mode == NEA_CELL_MODE_FORWARD)
    {
        if (tick_f32 >= total)
        {
            *finished = true;
            return total - 1;
        }
        return tick_f32;
    }

    if (seq->mode == NEA_CELL_MODE_FORWARD_LOOP)
        return tick_f32 % total;

    int32_t period = total * 2;
    int32_t u;
    if (seq->mode == NEA_CELL_MODE_PINGPONG)
    {
        if (tick_f32 >= period)
        {
            *finished = true;
            return 0;
        }
        u = tick_f32;
    }
    else
    {
        u = tick_f32 % period;
    }

    return (u < total) ? u : (period - 1 - u);
}

ARM_CODE static int ne_cell_frame_at(const NEA_CellData *data,
                                     int seq_index, int32_t pos_f32,
                                     int32_t *frac)
{
    const NEA_CellSequence *seq = &data->sequences[seq_index];
    const uint16_t *prefix = data->seq_prefix
                           + data->seq_prefix_base[seq_index];

    int tick = pos_f32 >> 12;
    int lo = 0;
    int hi = seq->num_frames - 1;
    while (lo < hi)
    {
        int mid = (lo + hi + 1) >> 1;
        if (prefix[mid] <= tick)
            lo = mid;
        else
            hi = mid - 1;
    }

    uint16_t duration = data->frames[seq->first_frame + lo].duration;
    if (duration == 0)
        duration = 1;

    int32_t f = divf32(pos_f32 - ((int32_t)prefix[lo] << 12), duration << 12);
    if (f < 0)
        f = 0;
    else if (f >= (1 << 12))
        f = (1 << 12) - 1;
    *frac = f;
    return lo;
}

typedef struct {
    uint32_t rot;
    int32_t sx, sy;
    int32_t px, py;
} ne_cell_srt_t;

ARM_CODE static void ne_cell_frame_srt(const NEA_CellData *data,
                                       const NEA_CellSequence *seq,
                                       int index, int32_t frac,
                                       ne_cell_srt_t *out)
{
    const NEA_CellFrame *f = &data->frames[seq->first_frame + index];

    out->rot = f->rot;
    out->sx = f->sx;
    out->sy = f->sy;
    out->px = f->px;
    out->py = f->py;

    if (seq->interp != NEA_CELL_INTERP_LINEAR || frac == 0
        || seq->num_frames < 2)
        return;

    int next = index + 1;
    if (next >= seq->num_frames)
    {
        if (seq->mode != NEA_CELL_MODE_FORWARD_LOOP
            && seq->mode != NEA_CELL_MODE_PINGPONG_LOOP)
            return;
        next = 0;
    }

    const NEA_CellFrame *g = &data->frames[seq->first_frame + next];
    out->rot = (uint32_t)ne_cell_rot_lerp(f->rot, g->rot, frac);
    out->sx = f->sx + mulf32(g->sx - f->sx, frac);
    out->sy = f->sy + mulf32(g->sy - f->sy, frac);
    out->px = f->px + (((g->px - f->px) * frac) >> 12);
    out->py = f->py + (((g->py - f->py) * frac) >> 12);
}

// Resolve one cell's parts under an outer transform, appending to the pose.
//
// Parts are walked in array order, which the loader has already checked is
// parents-before-children, so a child reads its parent's finished transform
// out of `resolved` without needing a second pass.
ARM_CODE static int ne_cell_pose_cell(NEA_CellAnim *anim, int cell_index,
                                      const ne_xform_t *base,
                                      const NEA_CellTrack **tracks,
                                      const int32_t *track_values,
                                      int num_tracks, int out_at)
{
    const NEA_CellData *data = anim->data;
    if (cell_index < 0 || cell_index >= data->num_cells)
        return out_at;

    const NEA_CellCell *cell = &data->cells[cell_index];
    ne_xform_t *resolved = anim->xform_scratch;

    for (int i = 0; i < cell->num_parts; i++)
    {
        const NEA_CellPart *part = &data->parts[cell->first_part + i];

        // Gather this part's animated channels. A rig carries a handful of
        // tracks, so a linear scan beats keeping a per-part index around.
        int32_t v_tx = 0, v_ty = 0, v_sx = 1 << 12, v_sy = 1 << 12;
        uint32_t v_rot = 0;
        int32_t v_alpha = part->alpha;
        int32_t v_color = part->color;
        int v_visible = (part->flags & NEA_CELL_PART_HIDDEN) ? 0 : 1;
        int v_swap = -1;

        for (int t = 0; t < num_tracks; t++)
        {
            if (tracks[t]->part != i)
                continue;
            int32_t value = track_values[t];
            switch (tracks[t]->channel)
            {
                case NEA_CELL_CH_TX:       v_tx = value; break;
                case NEA_CELL_CH_TY:       v_ty = value; break;
                case NEA_CELL_CH_ROT:      v_rot = (uint32_t)value; break;
                case NEA_CELL_CH_SX:       v_sx = value; break;
                case NEA_CELL_CH_SY:       v_sy = value; break;
                case NEA_CELL_CH_ALPHA:    v_alpha = value; break;
                case NEA_CELL_CH_COLOR:    v_color = value; break;
                case NEA_CELL_CH_VISIBLE:  v_visible = value ? 1 : 0; break;
                case NEA_CELL_CH_PARTSWAP: v_swap = value; break;
                default: break;
            }
        }

        ne_xform_t local;
        if ((v_rot & 0xFFFF) == 0 && v_sx == (1 << 12) && v_sy == (1 << 12)
            && v_tx == 0 && v_ty == 0)
        {
            local = NE_XFORM_IDENTITY;
        }
        else
        {
            ne_xform_srt(v_rot, v_sx, v_sy,
                         (int32_t)part->pivot_x << 12,
                         (int32_t)part->pivot_y << 12,
                         v_tx, v_ty, &local);
        }

        if (part->parent >= 0 && part->parent < i)
        {
            ne_xform_t composed;
            ne_xform_compose(&resolved[part->parent], &local, &composed);
            local = composed;
        }
        resolved[i] = local;

        if (out_at >= anim->pose_capacity)
            break;

        ne_xform_t world;
        ne_xform_compose(base, &local, &world);

        NEA_CellPartXform *out = &anim->pose[out_at];
        out->part = part;

        const NEA_CellPart *src = part;
        if (v_swap >= 0 && v_swap < cell->num_parts)
            src = &data->parts[cell->first_part + v_swap];
        out->src = src;

        out->m[0] = world.m[0];
        out->m[1] = world.m[1];
        out->m[2] = world.m[2];
        out->m[3] = world.m[3];
        ne_xform_apply(&world, (int32_t)part->off_x << 12,
                       (int32_t)part->off_y << 12, &out->tx, &out->ty);

        if (v_alpha < 0) v_alpha = 0; else if (v_alpha > 31) v_alpha = 31;
        out->alpha = (uint8_t)v_alpha;
        out->color = (uint16_t)(v_color & 0x7FFF);
        out->priority = part->priority > 3 ? 3 : part->priority;
        out->visible = (uint8_t)v_visible;

        out_at++;
    }

    return out_at;
}

// The sentinel `sequence` value for an instance seated on a multi-cell rather
// than playing a sequence of its own.
#define NE_CELL_SEQ_NONE 0xFFFF

// The point of a cell that its position refers to, and that the instance
// transform turns about. In f32 cell-space pixels.
//
// Shared with NEACellDraw.c rather than duplicated, because a billboard that
// stands on a different point from the one it spins about is a bug nobody
// would think to look for.
void __NEA_CellAnchorPoint(const NEA_CellAnim *anim, int cell_index,
                           int32_t *ax, int32_t *ay)
{
    *ax = 0;
    *ay = 0;

    const NEA_CellData *data = anim->data;
    if (data == NULL || cell_index < 0 || cell_index >= data->num_cells)
        return;

    const NEA_CellCell *cell = &data->cells[cell_index];

    switch (anim->anchor)
    {
        case NEA_CELL_ANCHOR_TOPLEFT:
            break;
        case NEA_CELL_ANCHOR_BOTTOM:
            *ax = (int32_t)(cell->min_x + cell->max_x) << 11; // half of << 12
            *ay = (int32_t)cell->max_y << 12;
            break;
        default:
            *ax = (int32_t)(cell->min_x + cell->max_x) << 11;
            *ay = (int32_t)(cell->min_y + cell->max_y) << 11;
            break;
    }
}

static void ne_cell_release_children(NEA_CellAnim *anim);
static int ne_cell_seat_multicell(NEA_CellAnim *anim, int multicell);

int NEA_CellAnimEvaluate(NEA_CellAnim *anim)
{
    NEA_AssertPointer(anim, "NULL animation");

    anim->pose_count = 0;
    if (anim->data == NULL)
        return 0;

    const NEA_CellData *data = anim->data;

    // Seated on a multi-cell: the children hold the poses, so there is nothing
    // to resolve here beyond letting each of them run its own clock.
    if (anim->sequence == NE_CELL_SEQ_NONE)
    {
        for (int i = 0; i < anim->num_children; i++)
            NEA_CellAnimEvaluate(anim->children[i]);
        return 0;
    }

    if (anim->sequence >= data->num_sequences)
        return 0;

    const NEA_CellSequence *seq = &data->sequences[anim->sequence];
    int32_t total = seq->total_ticks ? seq->total_ticks : 1;

    bool finished = false;
    int32_t pos = ne_cell_resolve_position(seq, total, anim->currtick,
                                           &finished);
    anim->finished = finished;

    // The instance transform sits outside everything the file describes, so a
    // caller can spin or squash a whole character without touching its data.
    //
    // It turns about the cell's anchor, not about the cell origin. Those are
    // the same point only for a bank whose art happens to be centred on it;
    // for anything else -- a character packed with its origin at its feet, say
    // -- rotating about the origin swings the sprite around in an arc instead
    // of spinning it in place. Which cell is on screen is not known until the
    // frame is resolved, so that has to happen first.
    ne_xform_t instance = NE_XFORM_IDENTITY;
    bool has_instance = anim->rot != 0 || anim->scale_x != (1 << 12)
                     || anim->scale_y != (1 << 12);

    if (seq->kind == NEA_CELL_KIND_RIG)
    {
        if (has_instance)
        {
            int32_t ax, ay;
            __NEA_CellAnchorPoint(anim, seq->cell, &ax, &ay);
            ne_xform_srt((uint32_t)((anim->rot & 511) << 7),
                         anim->scale_x, anim->scale_y, ax, ay, 0, 0,
                         &instance);
        }
        anim->pose_cell = seq->cell;

        const NEA_CellTrack *tracks[NEA_CELL_CH_COUNT * 16];
        int32_t values[NEA_CELL_CH_COUNT * 16];
        int n = seq->num_tracks;
        if (n > (int)(sizeof(tracks) / sizeof(tracks[0])))
            n = sizeof(tracks) / sizeof(tracks[0]);

        for (int i = 0; i < n; i++)
        {
            tracks[i] = &data->tracks[seq->first_track + i];
            values[i] = ne_cell_eval_track(data, tracks[i], pos);
        }

        anim->pose_count = ne_cell_pose_cell(anim, seq->cell, &instance,
                                             tracks, values, n, 0);
        return anim->pose_count;
    }

    if (seq->num_frames == 0)
        return 0;

    int32_t frac;
    int index = ne_cell_frame_at(data, anim->sequence, pos, &frac);
    ne_cell_srt_t srt;
    ne_cell_frame_srt(data, seq, index, frac, &srt);
    const NEA_CellFrame *frame = &data->frames[seq->first_frame + index];

    if (seq->kind == NEA_CELL_KIND_MULTI)
    {
        // Re-seat only when the frame actually names a different multi-cell,
        // so a looping node keeps its phase across frames that do not change
        // the composition.
        if (frame->target != anim->multicell || anim->num_children == 0)
            ne_cell_seat_multicell(anim, frame->target);

        anim->multi_px = (int16_t)srt.px;
        anim->multi_py = (int16_t)srt.py;

        for (int i = 0; i < anim->num_children; i++)
            NEA_CellAnimEvaluate(anim->children[i]);
        return 0;
    }

    // KIND_CELL: one whole-cell scale/rotate/translate about the cell origin.
    // That one is retail's and stays as it is; the instance transform on top
    // of it pivots on the anchor.
    anim->pose_cell = frame->target;

    if (has_instance)
    {
        int32_t ax, ay;
        __NEA_CellAnchorPoint(anim, frame->target, &ax, &ay);
        ne_xform_srt((uint32_t)((anim->rot & 511) << 7),
                     anim->scale_x, anim->scale_y, ax, ay, 0, 0, &instance);
    }

    ne_xform_t base;
    ne_xform_srt(srt.rot, srt.sx, srt.sy, 0, 0,
                 srt.px << 12, srt.py << 12, &base);
    ne_xform_t composed;
    ne_xform_compose(&instance, &base, &composed);

    anim->pose_count = ne_cell_pose_cell(anim, frame->target, &composed,
                                         NULL, NULL, 0, 0);
    return anim->pose_count;
}

const NEA_CellPartXform *NEA_CellAnimGetPose(const NEA_CellAnim *anim,
                                             int *count)
{
    NEA_AssertPointer(anim, "NULL animation");
    if (count)
        *count = anim->pose_count;
    return anim->pose;
}

//-----------------------------------------------------------------------------
// Instances
//-----------------------------------------------------------------------------

int NEA_CellSystemReset(int max_anims)
{
    if (ne_cell_system_inited)
        NEA_CellSystemEnd();

    if (max_anims < 1)
        max_anims = NEA_DEFAULT_CELL_ANIMS;

    ne_cell_anims = calloc(max_anims, sizeof(NEA_CellAnim *));
    if (ne_cell_anims == NULL)
    {
        NEA_DebugPrint("NEACell: not enough memory");
        return -1;
    }

    ne_cell_max_anims = max_anims;
    ne_cell_system_inited = true;
    return 0;
}

void NEA_CellSystemEnd(void)
{
    if (!ne_cell_system_inited)
        return;

    NEA_CellAnimDeleteAll();

    free(ne_cell_anims);
    ne_cell_anims = NULL;
    ne_cell_max_anims = 0;
    ne_cell_system_inited = false;
    __ne_cell_camera = NULL;
}

NEA_CellAnim *NEA_CellAnimCreate(void)
{
    if (!ne_cell_system_inited)
    {
        NEA_DebugPrint("NEACell: system not initialized");
        return NULL;
    }

    for (int i = 0; i < ne_cell_max_anims; i++)
    {
        if (ne_cell_anims[i] != NULL)
            continue;

        NEA_CellAnim *anim = calloc(1, sizeof(NEA_CellAnim));
        if (anim == NULL)
        {
            NEA_DebugPrint("NEACell: not enough memory");
            return NULL;
        }

        anim->active = true;
        anim->speed = 1 << 12;
        anim->scale_x = 1 << 12;
        anim->scale_y = 1 << 12;
        anim->base_alpha = 31;
        anim->base_color = 0x7FFF;
        anim->units_per_pixel = floattof32(1.0f / 32.0f);
        anim->anchor = NEA_CELL_ANCHOR_CENTER;
        anim->sequence = NE_CELL_SEQ_NONE;
        anim->multicell = 0xFFFF;

        ne_cell_anims[i] = anim;
        return anim;
    }

    NEA_DebugPrint("NEACell: no free animation slots");
    return NULL;
}

static void ne_cell_release_children(NEA_CellAnim *anim)
{
    if (anim->children == NULL)
        return;
    for (int i = 0; i < anim->num_children; i++)
    {
        if (anim->children[i])
            NEA_CellAnimDelete(anim->children[i]);
    }
    free(anim->children);
    anim->children = NULL;
    anim->num_children = 0;
    anim->multicell = 0xFFFF;
}

void NEA_CellAnimDelete(NEA_CellAnim *anim)
{
    if (anim == NULL)
        return;

    // Weak reference: the hardware backend is a separate translation unit, so
    // a ROM that never bound OAM never links it and this resolves to NULL.
    extern void NEA_CellAnimUnbindOAM(NEA_CellAnim *anim) __attribute__((weak));
    if (anim->oam && NEA_CellAnimUnbindOAM)
        NEA_CellAnimUnbindOAM(anim);

    ne_cell_release_children(anim);

    free(anim->pose);
    free(anim->xform_scratch);

    for (int i = 0; i < ne_cell_max_anims; i++)
    {
        if (ne_cell_anims[i] == anim)
        {
            ne_cell_anims[i] = NULL;
            break;
        }
    }

    free(anim);
}

void NEA_CellAnimDeleteAll(void)
{
    if (ne_cell_anims == NULL)
        return;
    for (int i = 0; i < ne_cell_max_anims; i++)
    {
        if (ne_cell_anims[i])
            NEA_CellAnimDelete(ne_cell_anims[i]);
    }
}

int NEA_CellAnimSetData(NEA_CellAnim *anim, const NEA_CellData *data)
{
    NEA_AssertPointer(anim, "NULL animation");
    NEA_AssertPointer(data, "NULL data");

    ne_cell_release_children(anim);

    // The pose and the scratch transforms are sized for the largest cell in
    // the bank, once, so playback never allocates.
    int capacity = data->max_parts_any_cell;
    if (capacity < 1)
        capacity = 1;

    NEA_CellPartXform *pose = calloc(capacity, sizeof(NEA_CellPartXform));
    ne_xform_t *scratch = calloc(capacity, sizeof(ne_xform_t));
    if (pose == NULL || scratch == NULL)
    {
        free(pose);
        free(scratch);
        NEA_DebugPrint("NEACell: not enough memory for a pose buffer");
        return -1;
    }

    free(anim->pose);
    free(anim->xform_scratch);
    anim->pose = pose;
    anim->xform_scratch = scratch;
    anim->pose_capacity = capacity;
    anim->pose_count = 0;

    anim->data = data;
    anim->sequence = NE_CELL_SEQ_NONE;
    anim->currtick = 0;
    anim->playing = false;
    anim->finished = false;
    return 0;
}

int NEA_CellAnimPlay(NEA_CellAnim *anim, int seq, int32_t speed)
{
    NEA_AssertPointer(anim, "NULL animation");
    if (anim->data == NULL)
        return -1;
    if (seq < 0 || seq >= anim->data->num_sequences)
    {
        NEA_DebugPrint("NEACell: sequence %d is out of range", seq);
        return -1;
    }

    // A CELL or RIG sequence has no nodes, so drop any the instance was
    // holding from an earlier multi-cell.
    if (anim->data->sequences[seq].kind != NEA_CELL_KIND_MULTI)
        ne_cell_release_children(anim);

    anim->sequence = seq;
    anim->currtick = 0;
    anim->playing = true;
    anim->finished = false;
    if (speed != 0)
        anim->speed = speed;

    NEA_CellAnimEvaluate(anim);
    return 0;
}

int NEA_CellAnimPlayNamed(NEA_CellAnim *anim, const char *name, int32_t speed)
{
    NEA_AssertPointer(anim, "NULL animation");
    if (anim->data == NULL)
        return -1;

    int seq = NEA_CellFindSequence(anim->data, name);
    if (seq < 0)
    {
        NEA_DebugPrint("NEACell: no sequence named '%s'", name);
        return -1;
    }
    return NEA_CellAnimPlay(anim, seq, speed);
}

// Seat one child instance per node of a multi-cell.
//
// Each child keeps its own clock, which is the whole point: a looping cape and
// a one-shot sword swing belong to one entity without being resampled onto a
// shared frame counter.
static int ne_cell_seat_multicell(NEA_CellAnim *anim, int multicell)
{
    const NEA_CellData *data = anim->data;
    if (data == NULL || multicell < 0 || multicell >= data->num_multicells)
        return -1;

    ne_cell_release_children(anim);

    const NEA_CellMultiCell *mc = &data->multicells[multicell];
    if (mc->num_nodes == 0)
        return 0;

    anim->children = calloc(mc->num_nodes, sizeof(NEA_CellAnim *));
    if (anim->children == NULL)
    {
        NEA_DebugPrint("NEACell: not enough memory for multi-cell nodes");
        return -1;
    }

    for (int i = 0; i < mc->num_nodes; i++)
    {
        const NEA_CellNode *node = &data->nodes[mc->first_node + i];

        NEA_CellAnim *child = NEA_CellAnimCreate();
        if (child == NULL)
        {
            NEA_DebugPrint("NEACell: ran out of slots seating a multi-cell");
            break;
        }
        anim->children[i] = child;
        anim->num_children = i + 1;

        if (NEA_CellAnimSetData(child, data) != 0)
            break;

        child->is_child = true;
        child->node_x = node->x;
        child->node_y = node->y;
        child->node_priority = node->priority;
        child->anchor = anim->anchor;
        NEA_CellAnimPlay(child, node->seq, anim->speed);
        if (node->flags & 1)
            child->playing = false;

        // If the parent is already bound to the hardware backend, the child
        // has to be too -- otherwise seating a multi-cell after binding
        // silently produces an entity that draws as quads but not as sprites.
        // Weak reference: NEACellOAM.c is only linked when something binds.
        extern void __NEA_CellBindChildOAM(NEA_CellAnim *, NEA_CellAnim *)
            __attribute__((weak));
        if (anim->oam && __NEA_CellBindChildOAM)
            __NEA_CellBindChildOAM(anim, child);
    }

    anim->multicell = multicell;
    return 0;
}

int NEA_CellAnimPlayMulti(NEA_CellAnim *anim, int multicell)
{
    NEA_AssertPointer(anim, "NULL animation");
    if (anim->data == NULL)
        return -1;

    if (ne_cell_seat_multicell(anim, multicell) != 0)
        return -1;

    anim->sequence = NE_CELL_SEQ_NONE;
    anim->currtick = 0;
    anim->playing = true;
    anim->finished = false;
    anim->multi_px = 0;
    anim->multi_py = 0;
    return 0;
}

NEA_CellAnim *NEA_CellAnimGetNode(NEA_CellAnim *anim, int node)
{
    NEA_AssertPointer(anim, "NULL animation");
    if (node < 0 || node >= anim->num_children)
        return NULL;
    return anim->children[node];
}

void NEA_CellAnimStop(NEA_CellAnim *anim)
{
    NEA_AssertPointer(anim, "NULL animation");
    anim->playing = false;
    anim->currtick = 0;
    anim->finished = false;
    for (int i = 0; i < anim->num_children; i++)
    {
        if (anim->children[i])
            NEA_CellAnimStop(anim->children[i]);
    }
}

void NEA_CellAnimPause(NEA_CellAnim *anim, bool paused)
{
    NEA_AssertPointer(anim, "NULL animation");
    anim->playing = !paused;
}

void NEA_CellAnimSetSpeed(NEA_CellAnim *anim, int32_t speed)
{
    NEA_AssertPointer(anim, "NULL animation");
    anim->speed = speed;
}

void NEA_CellAnimSetTick(NEA_CellAnim *anim, int32_t tick)
{
    NEA_AssertPointer(anim, "NULL animation");
    anim->currtick = tick < 0 ? 0 : tick;
    anim->finished = false;
    NEA_CellAnimEvaluate(anim);
}

int32_t NEA_CellAnimGetTick(const NEA_CellAnim *anim)
{
    NEA_AssertPointer(anim, "NULL animation");
    return anim->currtick;
}

int NEA_CellAnimGetFrame(const NEA_CellAnim *anim)
{
    NEA_AssertPointer(anim, "NULL animation");
    if (anim->data == NULL || anim->sequence == NE_CELL_SEQ_NONE
        || anim->sequence >= anim->data->num_sequences)
        return -1;

    const NEA_CellSequence *seq = &anim->data->sequences[anim->sequence];
    if (seq->num_frames == 0)
        return -1;

    bool finished;
    int32_t total = seq->total_ticks ? seq->total_ticks : 1;
    int32_t pos = ne_cell_resolve_position(seq, total, anim->currtick,
                                           &finished);
    int32_t frac;
    return ne_cell_frame_at(anim->data, anim->sequence, pos, &frac);
}

bool NEA_CellAnimIsFinished(const NEA_CellAnim *anim)
{
    NEA_AssertPointer(anim, "NULL animation");
    return anim->finished;
}

void NEA_CellAnimSetParams(NEA_CellAnim *anim, uint8_t alpha,
                           uint8_t poly_id, uint16_t color)
{
    NEA_AssertPointer(anim, "NULL animation");
    anim->base_alpha = alpha > 31 ? 31 : alpha;
    anim->base_poly_id = poly_id & 0x3F;
    anim->base_color = color & 0x7FFF;
}

void NEA_CellAnimSetTransformI(NEA_CellAnim *anim, int rot,
                               int32_t sx, int32_t sy)
{
    NEA_AssertPointer(anim, "NULL animation");
    anim->rot = rot;
    anim->scale_x = sx;
    anim->scale_y = sy;
}

void NEA_CellAnimSetCamera(NEA_Camera *camera)
{
    __ne_cell_camera = camera;
}

void NEA_CellAnimSetUnitsPerPixelI(NEA_CellAnim *anim, int32_t upp)
{
    NEA_AssertPointer(anim, "NULL animation");
    anim->units_per_pixel = upp;
}

void NEA_CellAnimSetAnchor(NEA_CellAnim *anim, NEA_CellAnchor anchor)
{
    NEA_AssertPointer(anim, "NULL animation");
    anim->anchor = (uint8_t)anchor;
}

void NEA_CellAnimUpdate(NEA_CellAnim *anim)
{
    NEA_AssertPointer(anim, "NULL animation");
    if (anim->data == NULL)
        return;

    if (anim->playing && !anim->finished)
        anim->currtick += anim->speed;

    // Advance the nodes before evaluating, because the parent's evaluate is
    // what re-poses them: doing it the other way round leaves every node one
    // tick behind the entity it belongs to.
    for (int i = 0; i < anim->num_children; i++)
    {
        NEA_CellAnim *child = anim->children[i];
        if (child && child->playing && !child->finished)
            child->currtick += child->speed;
    }

    NEA_CellAnimEvaluate(anim);
}

void NEA_CellAnimUpdateAll(void)
{
    if (!ne_cell_system_inited)
        return;

    for (int i = 0; i < ne_cell_max_anims; i++)
    {
        NEA_CellAnim *anim = ne_cell_anims[i];
        // Multi-cell nodes are advanced by their parent. Stepping them here
        // as well would run them at double speed.
        if (anim && anim->active && anim->data && !anim->is_child)
            NEA_CellAnimUpdate(anim);
    }
}
