// SPDX-License-Identifier: CC0-1.0
//
// SPDX-FileContributor: Warioware64, 2026
//
// This file is part of Nitro Engine Advanced
//
// Hardware 2D text rendering example
// -----------------------------------
// Renders text onto a 16bpp bitmap background using the libdsf font system
// (NEA_Hw2DTextRender). The font is loaded from compiled-in data using
// NEA_RichTextBitmapSet with GL_RGBA (A1RGB5) format.
//
// D-pad moves the text position. B clears.
// L/R change 3D layer priority. X/Y change 2D BG priority.

#include <stdio.h>

#include <NEAMain.h>

// Font texture (A1RGB5 16bpp) generated by grit from font2_0_16bit.png
#include "font2_0_16bit.h"
// Font metadata (BMFont binary format)
#include "font2_fnt_bin.h"

typedef struct {
    NEA_Camera *camera;
} SceneData;

void Draw3DScene(void *arg)
{
    SceneData *scene = arg;
    NEA_CameraUse(scene->camera);

    NEA_PolyFormat(31, 0, NEA_LIGHT_0, NEA_CULL_NONE, 0);

    GFX_BEGIN = GL_TRIANGLES;

    GFX_COLOR = RGB15(31, 0, 0);
    glVertex3v16(floattov16(-1.0), floattov16(-1.0), 0);

    GFX_COLOR = RGB15(0, 31, 0);
    glVertex3v16(floattov16(1.0), floattov16(-1.0), 0);

    GFX_COLOR = RGB15(0, 0, 31);
    glVertex3v16(floattov16(0.0), floattov16(1.0), 0);

    GFX_END = 0;
}

int main(int argc, char *argv[])
{
    (void)argc;
    (void)argv;

    SceneData scene = { 0 };

    irqEnable(IRQ_HBLANK);
    irqSet(IRQ_VBLANK, NEA_VBLFunc);
    irqSet(IRQ_HBLANK, NEA_HBLFunc);

    NEA_SetTexPaletteBank(NEA_VRAM_F);
    NEA_Init3D();

    NEA_Hw2DVRAMConfig cfg = {
        .main_bg  = NEA_VRAM_E,
        .main_obj = 0,
        .sub_bg   = 0,
        .sub_obj  = 0,
    };
    NEA_Hw2DInit(&cfg);

    scene.camera = NEA_CameraCreate();
    NEA_CameraSet(scene.camera,
                  0, 0, 3,
                  0, 0, 0,
                  0, 1, 0);

    NEA_LightSet(0, NEA_White, 0, -1, -1);

    // 3D clear color with alpha=0: transparent, shows bitmap BG behind
    NEA_ClearColorSet(NEA_Black, 0, 63);

    // 16bpp bitmap BG on layer 2 (MODE_5_3D required for bitmap)
    NEA_Hw2DBG *bg = NEA_Hw2DBGCreate(NEA_ENGINE_MAIN, 2,
                                       NEA_HW2D_BG_BITMAP_16, 256, 256);

    int bg2_priority = 3;
    NEA_Hw2DBGSetPriority(bg, bg2_priority);

    // 3D renders on BG0 — its priority determines front/back vs 2D BG
    int bg0_priority = (REG_BG0CNT >> 0) & 3;

    // --- Set up rich text font (libdsf) ---
    // Font slot 0: A1RGB5 (GL_RGBA) font for 16bpp bitmap rendering.
    // The font texture is 128x128 A1RGB5 converted by grit from a BMFont PNG.
    NEA_RichTextStartSystem(1);
    NEA_RichTextInit(0);
    NEA_RichTextMetadataLoadMemory(0, font2_fnt_bin, font2_fnt_bin_size);
    NEA_RichTextBitmapSet(0, font2_0_16bitBitmap, 128, 128,
                          NEA_A1RGB5, NULL, 0);

    // Initial text draw
    int text_x = 10, text_y = 10;
    NEA_Hw2DBGClearBitmap(bg, 0);  // 0 = transparent (no BIT(15))
    NEA_Hw2DTextRender(bg, 0, "NEA Hw2D Text Demo", text_x, text_y);
    NEA_Hw2DTextRender(bg, 0, "LibDSF font on\n16bpp bitmap BG", text_x, text_y + 30);

    // Console on sub screen
    consoleDemoInit();
    printf("NEA Hw2D Text BG Demo\n");
    printf("---------------------\n");
    printf("D-pad: move text position\n");
    printf("L/R: change 3D priority\n");
    printf("X/Y: change 2D BG priority\n");
    printf("B: clear bitmap\n");

    while (1)
    {
        NEA_WaitForVBL(NEA_UPDATE_HW2D);

        scanKeys();
        uint32_t keys = keysHeld();
        uint32_t down = keysDown();

        if (keys & KEY_RIGHT) text_x += 2;
        if (keys & KEY_LEFT)  text_x -= 2;
        if (keys & KEY_DOWN)  text_y += 2;
        if (keys & KEY_UP)    text_y -= 2;

        // Redraw text at new position every frame D-pad is held
        if (keys & (KEY_RIGHT | KEY_LEFT | KEY_DOWN | KEY_UP))
        {
            NEA_Hw2DBGClearBitmap(bg, 0);
            NEA_Hw2DTextRender(bg, 0, "NEA Hw2D Text Demo", text_x, text_y);
            NEA_Hw2DTextRender(bg, 0, "LibDSF font on\n16bpp bitmap BG",
                               text_x, text_y + 30);
        }

        if (down & KEY_B)
            NEA_Hw2DBGClearBitmap(bg, 0);

        // Cycle 3D layer (BG0) priority with L/R (0-3)
        if (down & KEY_R)
        {
            bg0_priority = (bg0_priority + 1) & 3;
            REG_BG0CNT = (REG_BG0CNT & ~BG_PRIORITY(3)) | BG_PRIORITY(bg0_priority);
        }
        if (down & KEY_L)
        {
            bg0_priority = (bg0_priority - 1) & 3;
            REG_BG0CNT = (REG_BG0CNT & ~BG_PRIORITY(3)) | BG_PRIORITY(bg0_priority);
        }

        // Cycle 2D BG priority with X/Y (0-3)
        if (down & KEY_X)
        {
            bg2_priority = (bg2_priority + 1) & 3;
            NEA_Hw2DBGSetPriority(bg, bg2_priority);
        }
        if (down & KEY_Y)
        {
            bg2_priority = (bg2_priority - 1) & 3;
            NEA_Hw2DBGSetPriority(bg, bg2_priority);
        }

        printf("\x1b[6;0HText pos: %d, %d   \n", text_x, text_y);
        printf("3D priority: %d | 2D BG: %d  \n", bg0_priority, bg2_priority);

        NEA_ProcessArg(Draw3DScene, &scene);
    }

    return 0;
}
